### ISSUE TITLE
Microsoft Edge Temp Graph Display Issue

### ISSUE THREAD

**Issue by ArmyAg08** [meteyou/mainsail#10]
The temperature graph shows a grey background (instead of transparent) as the temperature updates as seen in the picture below. 

![image](https://user-images.githubusercontent.com/2296277/80813734-36d98d00-8b90-11ea-9f43-fc491ef8cb42.png)

**Comment by translucentfocus** [comment]
I know this is a older post, but are you referring to [Microsoft Edge Legacy](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-sysupdate-access-old-edge)?

Using [mainsail-alpha-0.0.12](https://github.com/meteyou/mainsail/tree/v0.0.12) & version 83.0.478.37 (Official build) (64-bit) of Edge (Chromium-based) it works fine 😊

![Moonraker Chromium Edge](https://user-images.githubusercontent.com/26986716/82749209-2f5f6b00-9d6d-11ea-8ddc-c5c514fe87da.png)

**Comment by ArmyAg08** [comment]
It looks like it might be legacy then. It shows version 44.18362.449.0 for me. I do only see the issue when a heater is active though. I see both are disabled in your screenshot. You might try turning one on to see if you can replicate the behavior.
![image](https://user-images.githubusercontent.com/2296277/82755989-dc051100-9d9c-11ea-802d-3cd50abc5e0d.png)

**Comment by translucentfocus** [comment]
> 
> 
> It looks like it might be legacy then. It shows version 44.18362.449.0 for me. I do only see the issue when a heater is active though. I see both are disabled in your screenshot. You might try turning one on to see if you can replicate the behavior.
> ![image](https://user-images.githubusercontent.com/2296277/82755989-dc051100-9d9c-11ea-802d-3cd50abc5e0d.png)

Yes, that is legacy Edge which uses a [deprecated rendering engine called EdgeHTML](https://blog.mozilla.org/blog/2018/12/06/goodbye-edge/).

Ah, I re-tested and confirmed it works fine when using the latest version of Edge (now Chromium-based using the Blink rendering engine)

I don't know what @meteyou would like to do in this situation, but based on [Microsoft's words here](https://support.microsoft.com/en-us/help/4533505/what-is-microsoft-edge-legacy), I would recommend not trying to support it & allocate development efforts somewhere else.

**Comment by meteyou** [comment]
thx for testing different versions... if the problem is solved in the newest version of edge, i dont think i have to fix something there...
