### ISSUE TITLE
Retract/Extrude Rates are wrong.

### ISSUE THREAD

**Issue by al3ph** [meteyou/mainsail#100]
**Describe the bug:**\
Extrude/Retract speeds are wrong. 
1mm/s Is correct

Extruding at 5 mm/s executes.
G1 E50 F600
Which is 10mm/s

Extruding at 10 mm/s executes.
G1 E5 F1200
Which is 20mm/s

20mm/s
G1 E1 F3000
Which is 50mm/s

60mm/s
G1 E1 F6000
which is 100mm/s

**Expected behavior:**\
They should issue the right commands.

**Comment by meteyou** [comment]
fixed with this commit -> https://github.com/meteyou/mainsail/commit/08a106d9453912c3b85a8614b9a13d5ebf65d93b

**Comment by al3ph** [comment]
Ah is there a way of getting a newer build, as the install docs only mention 0.2.2
