### ISSUE TITLE
Refresh button in files list page not parse file (and display thumbnails)

### ISSUE THREAD

**Issue by manoukianv** [meteyou/mainsail#102]
**Describe the bug:**\
I use Samba to put gcode files in the virtual_sd, i press the refresh button, file is displayed but not thumbnails and are metadata are not parsed

**Expected behavior:**\
I expect when i click on the "refresh" it display thumbnails. What i think, it the refresh does not call setMetadata, but i'm bad in vue.js :-(
If i add a new directory, it seem to parse the file and display the thumbnails.

**Screenshots:**\
i use refresh : it display filename but not parse metada
![image](https://user-images.githubusercontent.com/10980775/95687240-b0c37700-0c02-11eb-908d-fc678141a53c.png)

i create a test directory, it parse the files and display thumbnails
![image](https://user-images.githubusercontent.com/10980775/95687301-eff1c800-0c02-11eb-9732-da4c414729e5.png)

**Comment by meteyou** [comment]
pls upload your log files! moonraker push the metadata, if it is ready.
