### ISSUE TITLE
[FR] integration options - MQTT?

### ISSUE THREAD

**Issue by thucar** [meteyou/mainsail#107]
**Is your feature request related to a problem? Please describe.**
I'm using smart plugs to control power to my printers. With Octoprint I would use a MQTT plugin to control the plugs. Would love to be able to do the same with Mainsail.

**Describe the solution you'd like**
Have a possibility to forward printer status updates over MQTT

**Describe alternatives you've considered**
Alternatively I will look into creating a one-off solution using my smart home system to communicate with Moonraker. But I suspect others would benefit from a MQTT integration as well.

**Additional context**
In OctoPrint I would look for printer status "Connected" and then turn on corresponding power plug and after 2 seconds I would send FIRMWARE_RESTART. Similarly if the printer status  would change to "Offline" I would turn off the plug

**Comment by meteyou** [comment]
Mainsail is only a webapp. it will execute only in your browser. so if i would implement MQTT in mainsail, you can only send MQTT commands if our pc is running and you are open mainsail in your browser. if you want to use mqtt without your pc or something else it have to be installed on your host (rpi or something else you run klipper & moonraker). so it would be better to implement it in moonraker than in mainsail, but i think it would be a overload to push all data from moonraker in your mqtt "network"...
