### ISSUE TITLE
Mainsail displays wrong object height in gcode manager

### ISSUE THREAD

**Issue by toskium** [meteyou/mainsail#113]
**Describe the bug:**\
SuperSlicer shows 21.80mm object height
Mainsail gcode manager shows 22.20mm object height

**Expected behavior:**\
Identical object height slicer/mainsail

**Screenshots:**\
![image](https://user-images.githubusercontent.com/15872792/97326600-726dbf00-1874-11eb-9802-1a69b6d55e7d.png)
![image](https://user-images.githubusercontent.com/15872792/97326635-7e598100-1874-11eb-9509-118478dee381.png)

**Buildplate as 3MF**\
[buildplate_3mf.zip](https://github.com/meteyou/mainsail/files/5446476/buildplate_3mf.zip)

**Logfiles:**\
[klippy.zip](https://github.com/meteyou/mainsail/files/5446452/klippy.zip)
[moonraker.zip](https://github.com/meteyou/mainsail/files/5446453/moonraker.zip)

**Comment by meteyou** [comment]
all gcode metadata is extracted by moonraker. there was an issue before and a description how this is done and therefore there can be "imprecisions". Arksine/moonraker#21

**Comment by toskium** [comment]
Ah, sorry to have bugged you with that. 
I added the fix suggested by Arksine and now it displays the correct object height.
