### ISSUE TITLE
Mainsail forgets "Printer Name" after reboot

### ISSUE THREAD

**Issue by pheonix3330** [meteyou/mainsail#115]
**Describe the bug:**\
"Printer Name" does not save when I turn my printer off. It resets to the default "raspberrypi" name instead of the name I set ("Voron V1.8").

**Expected behavior:**\
Mainsail remembers the printer name I set and restores it after reboot. This may be happening because I am cutting power to the MCU when I shut down the printer but I have the raspberry pi powered separately and the pi never turns off. When the printer turns off.

**Comment by randellhodges** [comment]
Are you pressing the "save" checkbox after making changes inside settings->interface? After you save, check the gui.json file and ensure it has the correct value in it?

**Comment by pheonix3330** [comment]
wow, didnt even know that button was there. I will do that now. Thanks for your help
