### ISSUE TITLE
[FR] display "Requested Speed"

### ISSUE THREAD

**Issue by bcmob** [meteyou/mainsail#116]
On the status panel, I really want to see the current requested speed.

moonraker gives it in the _gcode_move. speed_ object

An example of how this is implemented in DWC
![Знімок екрана 2020-10-31 о 10 54 01](https://user-images.githubusercontent.com/14820341/97775206-94fb2300-1b67-11eb-986a-cc8cb23d1294.png)

**Comment by meteyou** [comment]
oh thx! this value is new! I will implement it!

**Comment by meteyou** [comment]
pls check the new release. i added the requested speed in the status panel during a print. https://github.com/meteyou/mainsail/commit/b38b052004bd5c959c53df1e174801a50ba370ee
