### ISSUE TITLE
WebUI Interface Settings

### ISSUE THREAD

**Issue by yannvautrin** [meteyou/mainsail#117]
**Describe the bug:**\
Everytime I restart the WebUI, I have to re-enter the settings from the side panel to edit the webcam parameters...

**Expected behavior:**\
Would like an option to save interface settings

Thanks!

**Comment by meteyou** [comment]
on the right bottom, there is a save button...

**Comment by yannvautrin** [comment]
Thanks, sorry for being a noob.... I found it!

**Comment by meteyou** [comment]
I have to modify it... auto save or a better visibility action...

**Comment by zellneralex** [comment]
How about a pop up question if you leave that page and have unsaved changes?

**Comment by meteyou** [comment]
I don't like popups 😅... At the beginning of moonraker, it was only possible to upload files, when the printer is in idle mode. So we need the safe button, that the user can save the config after a print or something else. Now we can upload every time and I will directly upload the new settings for every button/switch...

**Comment by meteyou** [comment]
i implemented a autosave function
