### ISSUE TITLE
Removing space from file name doesn't change filename in status file list

### ISSUE THREAD

**Issue by dmnkhhn** [meteyou/mainsail#1187]
### Mainsail Version:

2.4.0

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

macOS

### What happened?

I have renamed a file (remove a space character) in the G-Code Files module, went back to the dashboard and tried printing the file from the file list in the status widget. The printing failed (Unable to open file) because the file still had it's old name with the space in it.
It worked after reloading the page.

### What did you expect to happen instead?

The status widget file list is updated when a file is renamed so that the printing can be started without reloading the page.

### How to reproduce this bug?

Upload a file with a space character in the name, rename the file and remove the space, go to the dashboard and try to print the file (or look at the file name). The space character is still in there and printing the file fails (Error: Unable to open file)

### Additional information:

The printer is running now and I can't test if this only happens with a space character or if it ignores a file rename regardless of the character.

**Comment by meteyou** [comment]
cannot reproduce this issue.

**Comment by dmnkhhn** [comment]
Interesting, I just updated all my packages and tried it again. I can confirm that it works for me now.

**Comment by meteyou** [comment]
Thx for the feedback.
