### ISSUE TITLE
[FR] Make printer.cfg editable in panel in dashboard.

### ISSUE THREAD

**Issue by r-franke** [meteyou/mainsail#119]
**Is your feature request related to a problem? Please describe.**
Often when I'm writing macro's I have to check coordinates and such. I have to either open up 2 windows to be able to edit the `printer.cfg` and look at the coordinates at the same time.

**Describe the solution you'd like**
Create an (optional) panel for the dashboard where we can edit the `printer.cfg`.

Maybe something like this:
![image](https://user-images.githubusercontent.com/67417714/98222691-745d0f80-1f51-11eb-957d-6c5dcfbf0e5c.png)

**Describe alternatives you've considered**
Another option would be to display a statusbar always on top with coordinates and temperature so that it's always visible in other screens.

**Comment by mattmon** [comment]
I too would appreciate a similar feature :+1:
 
This would ease switching between the separate configurations for each different tool head used with my TAZ 6.

Here's my take on @r-franke's suggestion:
![Screenshot from 2020-12-30 20-51-46](https://user-images.githubusercontent.com/924673/103395114-44f5f980-4ae1-11eb-9558-998feaaffab8.png)

**Comment by eliteSchwein** [comment]
Since i use alot printer.cfg and already changed alot in mainsail on my repo i will add a configuration panel for printer.cfg and will make a push request

**Comment by eliteSchwein** [comment]
Sorry i read the issue wrongly, i expected that mainsail doesnt have a printer.cfg editor, but it has so yeah i dont change anything at that part lol
