### ISSUE TITLE
Failed to restart klipper_mcu.service: Unit klipper_mcu.service not found.

### ISSUE THREAD

**Issue by Wilder-Kaiser** [meteyou/mainsail#1250]
### Mainsail Version:

2.4.1

### Browser:

Chrome

### Device:

Desktop PC

### Operating System:

Windows

### What happened?

To set up a RPi as Microcontroller, one hase to follow [these ](https://www.klipper3d.org/RPi_microcontroller.html) instructions.
By doing so one gets the error: 
Attempting host MCU restart...
Failed to restart klipper_mcu.service: Unit klipper_mcu.service not found.
make: *** [src/linux/Makefile:14: flash] Error 5

### What did you expect to happen instead?

No error message since it actually does work.

### How to reproduce this bug?

Just follow the instructions on https://www.klipper3d.org/RPi_microcontroller.html

### Additional information:

I did:
sudo find / -name klipper*.service
sudo systemctl restart klipper-mcu.service
ls /tmp
// socket file klipper_host_mcu 
sudo systemctl enable klipper-mcu.service //double check if enabled
systemctl list-unit-files | grep enabled | grep klipper // klipper-mcu.service and klipper.service enabled

**Comment by meteyou** [comment]
@Wilder-Kaiser can you explain to me what this problem should have to do with mainsail?

**Comment by Wilder-Kaiser** [comment]
@meteyou Hi, do you see this issue at klipper?

**Comment by meteyou** [comment]
mainsail is just a gui and you linked two times a klipper guide of a "klipper host mcu". so yes...

**Comment by meteyou** [comment]
yes, unfortunately, this is very often confused... thx for closing it.
