### ISSUE TITLE
[FR] Keep Speed, Extrusion, Baby Stepping, etc. visible whether printing or not 

### ISSUE THREAD

**Issue by yonkiman** [meteyou/mainsail#127]
**Is your feature request related to a problem? Please describe.**
I found myself unintentionally starting a print at 200% speed because that was where I'd left the slider after my previous print.  Similarly, I wanted to start a print with Baby Stepping at -0.05mm, but I can't adjust Baby Stepping until after the print has started.

**Describe the solution you'd like**
I understand the desire to have the GUI only show the controls needed for the mode the printer is in, but sometimes there are unintended side-effects (see above).  Also, having the same control page appear different depending on what mode you are in can be confusing, at least initially.  Recommend keeping the controls the same across all operational modes, or at least having a configuration option for that.

**Comment by meteyou** [comment]
maybe i can made this customizeable... until i add this "feature", you can reset all this settings in your start gcode. look in a prusa start gcode or my start_macro on my github repo (KlipperMisc). i reset all settings in my start_macro.
