### ISSUE TITLE
[FR] Emergency stop button location too close to browser menu on mobile.

### ISSUE THREAD

**Issue by cbc02009** [meteyou/mainsail#129]
**Is your feature request related to a problem? Please describe.**
The emergency stop button on mobile is too close to the menu buttons on most mobile browsers, and it's really easy for someone like me to fat-finger an emergency stop when all they wanted to do was open a new browser tab.

**Describe the solution you'd like**
I honestly don't know where a better place would be. Top left corner maybe? Or have a confirmation popup on mobile devices? I wish I had better suggestions.

**Describe alternatives you've considered**
I could just use my laptop, where this wouldn't be an issue, but having mobile support for mainsail is one of my favorite features of it.

**Additional context**
None.

**Comment by cbc02009** [comment]
Here's a screenshot to highlight the issue
![Screenshot_20201127-081922_Firefox](https://user-images.githubusercontent.com/39525900/100453751-81b97580-3089-11eb-99fc-1def025b3bd3.jpg)

**Comment by meteyou** [comment]
there is already a FR... https://github.com/meteyou/mainsail/issues/114

**Comment by cbc02009** [comment]
Oops. Sorry about that!
