### ISSUE TITLE
Power module doesn’t show after Moonraker update

### ISSUE THREAD

**Issue by LazaroFilm** [meteyou/mainsail#131]
**Describe the bug:**\
Moonraker changed how Power on/off is handled and broke the power module in Mainsail. 
**Expected behavior:**\
See the power module when it's configured. 
**Screenshots:**\

**Logfiles:**\
Please upload your Logfiles here or upload them to [pastebin.com](http://pastebin.com) and paste your log links here.
- klippy.log
- moonraker.log

**Comment by lixxbox** [comment]
Should work again in the coming update.

**Comment by meteyou** [comment]
@LazaroFilm pls try the new release and report...

**Comment by LazaroFilm** [comment]
Works since update
