### ISSUE TITLE
No preview gcode file thumbnails since 0.3.0

### ISSUE THREAD

**Issue by nklrk** [meteyou/mainsail#133]
**Describe the bug:**\
Since version 0.3.0 there is no preview thumbnail on the gcode file tab anymore. I don't know if this is a bug or a feature. But neither in the grid nor when clicking on a file there is no preview image shown. 

**Expected behavior:**\
There was a preview thumbnail in earlier releases.

**Screenshots:**\
![2020-11-28 12_55_47-Voron 2 4](https://user-images.githubusercontent.com/61452016/100515036-99702700-3179-11eb-82e7-f29301e64458.png)
![2020-11-28 12_56_02-Voron 2 4](https://user-images.githubusercontent.com/61452016/100515038-99702700-3179-11eb-89bd-3bc49e8c96d0.png)

**Comment by meteyou** [comment]
do you update the moonraker 
dependencies?

**Comment by nklrk** [comment]
Yes I did. Mainsail shows me "v0.9.1-23-g41c6b4b3-dirty"

**Comment by nklrk** [comment]
Ok please excuse me. Obviously there went something wrong while updating. I run the dependency update again, restarted the PI twice and now everything's fine again. Sorry for that 👍
