### ISSUE TITLE
[FR] Configurable movement buttons

### ISSUE THREAD

**Issue by al3ph** [meteyou/mainsail#134]
As my Voron V0 is only 120mm XYZ it'd be nice to have configurable move step sizes, as the 100mm step size is of limited use. 25mm like the Z axis make far more sense.

I imagine this is the case for most small printers.

cheers!

**Comment by Gilabite** [comment]
wouldnt mind this too but for opposite reason, 1000mm on Z and only being able to move 25 at a time and 100 would be nice lol

**Comment by al3ph** [comment]
That's just showing off :)

**Comment by meteyou** [comment]
this is already in my backlog... will come in one of the next versions. thx for the request... i will ping you, when i publish a version with this feature.

**Comment by meteyou** [comment]
will be in the next release! enjoy it!

**Comment by al3ph** [comment]
:) CHEERS!
