### ISSUE TITLE
[FR] Full-window button or gesture for the webcam view

### ISSUE THREAD

**Issue by zbrozek** [meteyou/mainsail#138]
Octoprint has a plugin which allows maximizing the webcam view to fill the browser window on double click. It'd be nice to have that functionality to be able to see better what's going on sometimes. Bonus points for putting some status information or a console bar at the bottom of that expanded view.

**Comment by meteyou** [comment]
thx for the FR. i have already thought about such a function. atm you can enable the webcam navi point to see the webcam stream as big as possible.

**Comment by zbrozek** [comment]
Aha, didn't realize that existed. Good enough, thanks!
