### ISSUE TITLE
Not an issue - just a wish :)

### ISSUE THREAD

**Issue by orkusmg** [meteyou/mainsail#14]
After ~35hrs of printing I woke up to this today
![2020-05-05_09h22_54](https://user-images.githubusercontent.com/49352823/81043293-4b7c9480-8eb2-11ea-976b-51fa1718d478.png)
![2020-05-05_09h23_06](https://user-images.githubusercontent.com/49352823/81043297-4e778500-8eb2-11ea-99b6-70bc9d45412a.png)

Situation seems safe for now as it already started to print mid air :) Exclude region/object should have high priority - running print like this is a high risk without such functionality for me. Happens rarerly but happens. If I may add - this has been aranged by Plater, hence it's a single stl so I'm not sure 'exclude object' would work, this is why I preffer 'Exclude region' in Octoprint, Maybe worth to consider.

**Comment by meteyou** [comment]
mainsail is only an interface of klipper. therefore klipper has to support it and i can only control the klipper plugin in mainsail. please send this request to the klipper team. octoprint is a standalone program which also handles the gcode which is a big difference to mainsail.
