### ISSUE TITLE
[FR] Support using an already probed mesh

### ISSUE THREAD

**Issue by zbrozek** [meteyou/mainsail#140]
Right now when trying to plot a heightmap of the bed, you have to re-run the mesh probing routine. It would be great if it were possible to use an in-memory mesh if one exists.

Further, pressing the calibrate button on a cold boot will usually fail because the axes haven't been homed first. Seems like there should be a more-elegant way to handle that, e.g., using the home axes command instead.

**Comment by meteyou** [comment]
selected your stored profile and click on "LOAD". this is the normal klipper why to load a profile! the whole heightmap page is a little bit buggy, because a havent time to rework it in the last api update.
