### ISSUE TITLE
File Editor Broken in Chrome on Android

### ISSUE THREAD

**Issue by jjgraphix** [meteyou/mainsail#142]
**Describe the bug:**\
When attempting to edit the printer.cfg, or any other file, from Chrome on my phone, the editor can't seem to recognize the correct lines of text. The type displays correctly but the cursor places itself between lines and words. Highlighting it shows there's a 'ghosted' duplicate of the text in the background that is offset and invisible (See pics).  This happens in both mobile and desktop modes.

It DOES seem to work correctly in the DuckDuckGo browser but I haven't tested other browsers on mobile yet.

_Issue has persisted between Mainsail 0.2.6 and 0.3.0._

**_Device Details:_**
Android 10
One UI Version: 2.5
Samsung Note 10+
Chrome Version: 87.0.4280.101

**Screenshots:**\
_Chrome Android (Mobile Version)_
![Mainsail_Chrome-bug1](https://user-images.githubusercontent.com/51905518/101835367-8aca2e00-3af0-11eb-80fb-bce9b9a50f39.jpg)

_Chrome Android (Desktop Mode)_
![Mainsail_Chrome-bug2](https://user-images.githubusercontent.com/51905518/101835363-8a319780-3af0-11eb-9b75-fe85f29420c8.jpg)

**Logfiles:**\
I assume logs aren't necessary but I'll provide anything you'd wish to see.

**Comment by meteyou** [comment]
i cannot reproduce this issue. maybe a update of the editor fixed it already.
