### ISSUE TITLE
Temp graph drops out during print at 238c on Nozzle and 70c on bed

### ISSUE THREAD

**Issue by MalsakerLures** [meteyou/mainsail#145]
My temp graph in Mainsail drops out during print at 238c on Nozzle and 70c on bed.
This does not happen when printing at lower temp around 235c and 65c.

There is no drop in actual temperature in either Nozzle or Bed and the print continous. When refreshing the webpage its works for a period of time.

Unable to add Moonraker.log as it in on 33mb
Klippy.log: https://pastebin.pl/view/c5b332be

<img width="1439" alt="Skärmavbild 2020-12-15 kl  23 04 09" src="https://user-images.githubusercontent.com/44981544/102279218-50ff8a00-3f2b-11eb-9af9-22d0cc3017a6.png">

**Comment by meteyou** [comment]
i changed the temp chart. pls test it again with the next release.

**Comment by MalsakerLures** [comment]
shall i update to the latest mainsail and moonraker?

**Comment by meteyou** [comment]
i will ping you, when i publish the next release.

**Comment by MalsakerLures** [comment]
Perfect! Thank you!

Skickat från min iPhone

**Comment by meteyou** [comment]
new release is published. pls test it again.

**Comment by MalsakerLures** [comment]
Seems to be working now👍👍

Skickat från min iPhone

**Comment by meteyou** [comment]
thx for the report!
