### ISSUE TITLE
[FR] Scrubber for values on plots

### ISSUE THREAD

**Issue by bcbuckles** [meteyou/mainsail#147]
Would be nice to be able to scrub over the plot and get a vertical line, and readout of all temperature values at that time value.  Like in Octoprint or other plotting libraries.  I often use this to look at trends in chamber temperature that don't show up well due to their small deltas that are less noticeable on the scale of Toolhead temp.

**Comment by meteyou** [comment]
yes. thats the reason, why i changed the chart libary. will come...

**Comment by bcbuckles** [comment]
> yes. thats the reason, why i changed the chart libary. will come...

Great news.  What's protocol here, should I delete the FR?

**Comment by meteyou** [comment]
No. Let it open, so others users can see, that it is a open feature. I will close it, if I fixed it.

**Comment by meteyou** [comment]
i added this feature. will be in the next release:

![image](https://user-images.githubusercontent.com/8167632/106343069-df458a80-62a3-11eb-96fd-a2032db9f1ae.png)
