### ISSUE TITLE
Heightmap doesn't show until refresh

### ISSUE THREAD

**Issue by bcbuckles** [meteyou/mainsail#148]
Clicking the heightmap tab, the UI says no heightmap loaded and there is no graph until you click refresh.  Then the heightmap shows up.

May be related to: https://github.com/meteyou/mainsail/issues/143#issue-765187014

**Comment by meteyou** [comment]
already fixed... https://github.com/meteyou/mainsail/commit/d1401d321a18c9f6b8fa0d35513b3a8a2de9949f
