### ISSUE TITLE
Cannot delete files which contain the '+' character in the file name.

### ISSUE THREAD

**Issue by nazzrim** [meteyou/mainsail#149]
**Describe the bug:**\
It is not possible to delete files via the mainsail UI if the filename contains the '+' character. After the file was renamed (via mainsail UI) it is working.
This happens in mainsail version 0.3.0

**Expected behavior:**\
Delete files which contain '+' in the file name.

**Screenshots:**\
![image](https://user-images.githubusercontent.com/4573229/102696655-2154c880-4230-11eb-98d9-d627a5f2ca16.png)
![image](https://user-images.githubusercontent.com/4573229/102696673-392c4c80-4230-11eb-978d-a087839b20a7.png)

**Logfiles:**\
[klippy.log](https://pastebin.com/kh2CkEhZ)
[moonraker.log](https://pastebin.com/fd51vb2x)

**Comment by meteyou** [comment]
I cannot open your logfiles. pls upload the Moonraker log again.

**Comment by nazzrim** [comment]
My bad. [Here](https://pastebin.com/0KUBUzyp) is the moonraker.log
