### ISSUE TITLE
High GPU usage even when mainsail browser window is minimized

### ISSUE THREAD

**Issue by cbc02009** [meteyou/mainsail#154]
**Describe the bug:**\
High GPU usage by mainsail browser window, even when the browser window is minimized: 
![image](https://user-images.githubusercontent.com/39525900/103359346-bbfda480-4a85-11eb-9840-2160b0af88fa.png)

from Firefox taskmanager:
![image](https://user-images.githubusercontent.com/39525900/103359376-d0da3800-4a85-11eb-81a0-47c2fe1555cb.png)

**Expected behavior:**\
I would expect the browser to not use many resources when minimized or hidden, so that I can keep it open on my laptop for emergencies, but not have it kill my laptop's battery.

If this should be a feature request instead of a bug report, please let me know, and I'll change it.

**Comment by meteyou** [comment]
pls send me your logfiles and tell me witch version do you use.

**Comment by cbc02009** [comment]
I'm using version v0.3.0

Here's the moonraker and klippy logs:
[moonraker.log](https://github.com/meteyou/mainsail/files/5755479/moonraker.log)
[klippy.log](https://github.com/meteyou/mainsail/files/5755480/klippy.log)

**Comment by meteyou** [comment]
ah ok. its the temp chart. pls update to 0.4.0. i changed the tempchart because of performace problems

**Comment by cbc02009** [comment]
Should have checked for an update first...

I'll close this if that fixes this. Thanks for the help.

**Comment by cbc02009** [comment]
@meteyou So that fixed half the problem. It definitely reduced the GPU usage from ~25% to ~1%, but it still uses ~4% cpu even when minimized or hidden, which has a drastic effect on my battery life.

I know literally nothing about web page design. Is it possible to stop drawing the graphs when the page is hidden or minimized (or just not the focus window)?

**Comment by meteyou** [comment]
let me check this performance... but i think is is only the websocket, if you minimice or hidden the window and this is necessary for mainsail. i think the graph is not drawing/rendering, if it is hidden...

**Comment by cbc02009** [comment]
I don't know if this is helpful, because the processor spikes make the averages hard to read, but here's my power usage on my desktop PC:

![tempsnip](https://user-images.githubusercontent.com/39525900/103481847-4ce8be80-4dab-11eb-9792-fee734474b2c.png)

The first part is with the window open and showing, consuming ~105w.

The second part is with the window open and minimized, consuming ~100w.

The third is with mainsail window closed, consuming ~90w.

**Comment by meteyou** [comment]
do you tested a newer release again?

**Comment by wormiedk** [comment]
Mine uses around 10% having mainsail open even if minimized / closed and if I hide both the temp graph and camera. Firefox drops to around 2% when closing the mainsail tab

**Comment by meteyou** [comment]
i cannot put mainsail in to a "sleep mode". otherwise a have to reinitial the while gui. its like a close and new opening of the while interface.

**Comment by jamiehs** [comment]
I'm seeing this same issue again.
High CPU usage when the window is in the background or minimized (or the display turns off). The only way I know it's happening is because I have aggressive fan curves on this (gaming) machine and I can hear them ramp up.

When I look at the Mainsail window, interactivity is sluggish, the webcam module is running at 1fps, and a refresh fixes the issue. I hear the fans instantly slow down, and the fps returns to a nominal 15-16 fps. I also observed this before adding a webcam to my setup, so I don't suspect it has much to do with the addition of the cam.

* Windows 10
* Chrome 90.0.4430.212 (Official Build) (64-bit)
* Mainsail 1.6.0

![image](https://user-images.githubusercontent.com/66539/118865099-7a835f80-b895-11eb-8132-6dca3c56d087.png)

**Comment by jamiehs** [comment]
Looked into this a bit more. It looks like it was related to the camera.
The Adaptive MJPEG-Streamer seems to be what is causing the issue. I switched to the regular MJPEG-Streamer and it's doing much better.

Sorry for the extra noise in this thread, but hopefully it could help someone else who is having issues with high CPU and memory use.
