### ISSUE TITLE
[FR] Optional / Alternate Jogging Controls

### ISSUE THREAD

**Issue by dspears0809** [meteyou/mainsail#155]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

An optional, alternate directional control panel that has a layout similar to what's used in Fluidd and OctoPrint with the centered home button, directional buttons, and movement distance (configurable movement distance selections which is already requested in Issue #134).

**Describe alternatives you've considered**

**Additional context**

**Comment by meteyou** [comment]
thx for the FR. I've been planning for a long time, but I haven't time to it yet.  please let the FR open until I've done it.

**Comment by meteyou** [comment]
@dspears0809 pls test the new release (v1.4.0). there is an alternative control option.
