### ISSUE TITLE
Wrong/old thumbnails are displayed

### ISSUE THREAD

**Issue by Metti93** [meteyou/mainsail#157]
**Describe the bug:**\
In the main GUI, after a successful print where a thumbnail was included, the exact same thumbnail is also displayed if you start G-Code without a thumbnail.
See screenshots

**Expected behavior:**\
Load G-code from Superslicer, with thumbnail, into Mainsail.
Start print and thumbnail is displayed correctly.

Load second G-code, without thumbnail, into mainsail.
The G-code did not display a thumbnail, as it should.
Start the second print and the thumbnail of the first print is displayed.

**Screenshots:**\
![image](https://user-images.githubusercontent.com/48029820/103466732-c4850200-4d47-11eb-8bce-9c7458d700b5.png)

![image](https://user-images.githubusercontent.com/48029820/103466741-db2b5900-4d47-11eb-9a71-6bd162300d76.png)

**Logfiles:**\
[klippy.log](https://github.com/meteyou/mainsail/files/5760885/klippy.log)
[moonraker.log](https://github.com/meteyou/mainsail/files/5760886/moonraker.log)

**Comment by eriroh** [comment]
I am experiencing the same thing and have not yet figured out a workaround except clicking (X) on the print.

**Comment by meteyou** [comment]
@eriroh you only have to refresh your browser tab.

**Comment by meteyou** [comment]
fixed with https://github.com/meteyou/mainsail/commit/e2e496c31e2995e220d22f67b3785feaea100d29
