### ISSUE TITLE
[FR] adjusting feedrates

### ISSUE THREAD

**Issue by jtrmal** [meteyou/mainsail#158]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to change the feedrates -- even for HF dragon and 0.4mm nozzle, the values over 13mm/s are just too much...

**Describe the solution you'd like**
Perhaps manual configuration of the feedrates or some additional tool for covering a specific interval of feed rates using the maximum volumetric flow?

**Describe alternatives you've considered**
I changed them in the js file (yes I know that implies I won't be able to update automatically)

**Additional context**
IMO probably a low priority, but perhaps useful?

**Comment by alexhocks** [comment]
+1 for this. My V6 can't handle anything more than 5mm/s so configuring the feed rates on the dashboard myself would be really nice.

**Comment by jtrmal** [comment]
thank you!
y.
