### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by lincolnep** [meteyou/mainsail#16]
1. Extrude filament option missing in the dashboard like dwc2 pic included.
![image](https://user-images.githubusercontent.com/3850303/81783905-a48d9d80-952e-11ea-8a93-5bed518ed2ee.png)

2. Editing of klippers printer.cfg file.

3. *(Nice to have)* Print from cura/slic3r/pursa slicer like octoprint/duet dwc2 maybe just use the duet dwc2 plugin until there is one coded for mainsail.

**Comment by meteyou** [comment]
1. is already on my todo list.
2. at the moment i have no API/moonraker posibillity todo this, but we are working on it
3. this is no point for the webinterface. only API/moonraker and it is already implemented. klick on octoprint and load your gcode up!
