### ISSUE TITLE
Update button no feedback 

### ISSUE THREAD

**Issue by barecool** [meteyou/mainsail#164]
**Describe the bug:**\
If printer is active (printing) update panel should be disabled
mainsail allows to press the update button, however no feedback is provided

**Expected behavior:**\
Panel should disable while printing / or provide a toast with feedback that updating is disabled while printing

**Screenshots:**\
![Screenshot (24)](https://user-images.githubusercontent.com/2767896/104202357-7380a800-53f0-11eb-90e6-0a14e3b79819.png)

**Logfiles:**\
[klippy.log](https://github.com/meteyou/mainsail/files/5796646/klippy.log)
[moonraker.log](https://github.com/meteyou/mainsail/files/5796650/moonraker.log)

**Comment by meteyou** [comment]
yes, this is a new moonraker feature. i have to implement it in mainsail... pls let this ticket open. i will close it, when i fixed it.

**Comment by meteyou** [comment]
i fixed it in https://github.com/meteyou/mainsail/commit/d05fa70832efc91b7a9a39384fac1c8665edc543. thx!
