### ISSUE TITLE
G-Code Files Viewer does not update metadata properly

### ISSUE THREAD

**Issue by toskium** [meteyou/mainsail#166]
**Describe the bug:**\
If you upload a gcode file, say "file.gcode" and it does not yet exist on the sdcard folder the file description in "g-code files" overview is generated.

If you reslice the same object and re upload the file with the same name, so the old version on the sdcard gets overwritten the meta-data isn't updated automatically.

It is not sufficient to re-click "g-code files" on the left-side menu you need to browser reload the tab (F5) or close/reopen the tab. 

**Expected behavior:**\
Clicking "G-Code Files" in the left-side menu should reload the sdcard content even though no change in the filename has been detected.

**Comment by meteyou** [comment]
fixed with https://github.com/meteyou/mainsail/commit/e2e496c31e2995e220d22f67b3785feaea100d29
