### ISSUE TITLE
[FR] Resource monitor

### ISSUE THREAD

**Issue by stefanpieter** [meteyou/mainsail#168]
A resource monitor for the RPi is very useful with parameters including:

1. CPU temp
2. CPU usage
3. Network usage

I love Mainsail! Complements to the developers.

**Comment by meteyou** [comment]
thx for your FR. CPU temp of a raspberry pi is currently available. only add this config to your printer.cfg:
```
[temperature_sensor raspberry_pi]
sensor_type: rpi_temperature
min_temp: 10
max_temp: 100
```

other values have to be added to moonraker or klipper to be available via the api. but i definitely want to be able to display more of them in the future.

**Comment by stefanpieter** [comment]
This is very useful.

Thank you!
