### ISSUE TITLE
[FR] Add Upload and Start print button on the dashboard

### ISSUE THREAD

**Issue by DorjeDorf** [meteyou/mainsail#170]
**Is your feature request related to a problem? Please describe.**
It's a usability feature I think. The way I see the use of Mainsail now, I have to go the Gcodes tab, upload a file, then click it to start printing. 

**Describe the solution you'd like**
Ideally, we'd see a button next to the Emergency Stop that would allow us to browse to a file, have it uploaded and print start automatically. Total rip off from DWC, but it does speed things up a lot ;)

**Describe alternatives you've considered**
None. Nice usability feature. 

**Additional context**
Nothing to add - basic feature in DWC. Would make Mainsail even more convenient to use.

**Comment by meteyou** [comment]
Ohh... You feature request was close before I released v1.0.0. pls update and enjoy the "upload & start" button in the topbar.

**Comment by DorjeDorf** [comment]
Now that's what I call amazing :)

Thanks, works perfectly!
