### ISSUE TITLE
Thumbnails are not displayed after update to 1.0

### ISSUE THREAD

**Issue by toskium** [meteyou/mainsail#171]
**Describe the bug:**\
In prior version 0.4.1 thumbnails have been displayed.
After update of mainsail to version 1.0.0 thumbnails don't appear.

**Expected behavior:**\
Thumbnails should appear.

**Screenshots:**\

![image](https://user-images.githubusercontent.com/15872792/105161918-3748f800-5b12-11eb-9f47-351c346ea593.png)

**Comment by pierre-vo** [comment]
`bugfix
display only 32x32 thumbnails in gcode files`

I think it is just more strict on the size of the small thumbnails. I had 64x64 and it was working, I expect it not to work anymore after the update from this part of the release note and will update my slicer to use 32x32.

Not sure though, I have not tested yet.

**Comment by toskium** [comment]
Thanks for the assist, 32x32 seems to be the only size that works. Too bad, I liked the big thumbs :-)

**Comment by meteyou** [comment]
it was only a bug. 32x32 is the correct size. i added a hover for the next version.
