### ISSUE TITLE
[FR] plot heater status (PWM value)

### ISSUE THREAD

**Issue by dewi-ny-je** [meteyou/mainsail#175]
When I heat up the bed the thermistor reaches the set value much earlier than the pwm value supplied to the heater stabilises, since it takes time for the heated bed to soak up the heat, especially when a glass plate is used on top of the aluminium bed.

Right now I look at the status value but depending on the set temperature the final steady state value is different and I don't remember all of them. Also, sometimes I print enclosed, sometimes not, so for the same set temperature the final steady state pwm value changes.

I think it would be very useful, for some users, to plot the pwm value together with the temperature graph, using obviously a second vertical scale which goes 0-100%.

This way I would be able to see with a quick glance whether the pwm value is stable or it's still decreasing.

This is especially useful for users with PID controller, but also users with bang-bang control would see whether the on/off intervals are equally spaced or still getting more rarified.

**Comment by meteyou** [comment]
i think that there is also a wrong result. i use 8mm aluminium plates and until they heat up, i can't even orientate myself to the pwm values. the bed heats up much faster at the bottom centre (where the sensor is) than on the top side up to the edges. the best variant for something like this is a second thermistor.

i will try it anyway to see how it would look. i just think that the pwm jumps too much and only one bar would be visible. i will post a screenshot, when i test it...

**Comment by dewi-ny-je** [comment]
Mine is quite consistent and it jumps only about 4% when it reaches equilibrium, but it's also true that I have a zero-crossing SSR for a 230V heater so the pwm resolution is 50 cycles/s *0.3 s = 15 power levels, which is 7% power steps

**Comment by meteyou** [comment]
i tested it and it will be a part of the next release!

![image](https://user-images.githubusercontent.com/8167632/106047932-81b70f80-60e4-11eb-8347-a717dc3aea5a.png)

**Comment by dewi-ny-je** [comment]
I don't know CanvasJS but if you want a nice UI I suggest putting labels on the vertical scales: PWM on one side and °C on the other side.
Pwm of course is wrong, since that axis has no unit of measure, but something is needed.

**Comment by meteyou** [comment]
thx for the feedback. i added units to both axis.

![image](https://cdn.discordapp.com/attachments/507697728797671425/804488466272223272/VcKjTwl2Cy.gif)
