### ISSUE TITLE
[FR] Support for thumbnails from Ideamaker

### ISSUE THREAD

**Issue by modmt** [meteyou/mainsail#180]
Hello,

is it possible to display thumbnails from the Slicer Ideamaker? That would be a nice feature for me, because I switched to Ideamaker from S3D and Prusaslicer. As I understand only Prusaslicer and Cura is supported at the moment regarding Thumbnails.

Thank you and best regards,
Matthias

**Comment by meteyou** [comment]
prusaslicer & cura writes the thumbnail into the file. does ideamaker do that too? if ideamaker does that too, moonraker could extract it and i could use it in mainsail. but the extracting itself happens in moonraker.

**Comment by modmt** [comment]
As I understood there is the possibility in Ideamaker to wrote Out an additional .Data File, which contains a Picture for displaying the model on the Raise3D Machines. But I do not know how this could be used.

I will ask this tomorrow in the moonraker git.
Thank you so far for your quick reply Stefan and Thank you too for your really good work with Mainsail.

**Comment by meteyou** [comment]
@modmt do you have any news for me?

**Comment by modmt** [comment]
Hello Stefan, unfortunatelly no update at the moment. I checked the .data file of Ideamaker but it seems to be that there is no easy way to extract this or at least I do not know how.
So I did not ask in the moonraker git for that until today. 
But I think I will do this this evening, maybe he knows a solution. I will give an update if I know more.

**Comment by meteyou** [comment]
are there any news about ideamaker thumbnails?

**Comment by julianobst** [comment]
Moonraker was up-to-date but I had no square format of the thumbnail set in IdeaMaker.
Setting the resolution to 400x400 (as you said) did the trick.

I guess this important information should be added to the mainsail docs: https://docs.mainsail.xyz/quicktips/thumbnails

Thanks for the fast reply and solution.
