### ISSUE TITLE
update manger / updating Moonraker fails

### ISSUE THREAD

**Issue by wuestner** [meteyou/mainsail#181]
**Describe the bug:**\
In the update-manager, moonraker shows the status "dirty".
Updating results in an error message: "Update aborted, repo is has been modified"

**Expected behavior:**\
Update if moonraker in GUI is possible.
**Screenshots:**\
<img width="953" alt="Screenshot 2021-01-31 191457" src="https://user-images.githubusercontent.com/72704588/106393681-d87c5c00-63f8-11eb-9f35-25de3896b4a8.png">

<img width="519" alt="Screenshot 2021-01-31 191706" src="https://user-images.githubusercontent.com/72704588/106393698-ef22b300-63f8-11eb-8dca-b8169ee0ea54.png">
**Logfiles:**\
Please upload your Logfiles here or upload them to [pastebin.com](http://pastebin.com) and paste your log links here.

https://pastebin.com/bmZ05XpY

**Comment by meteyou** [comment]
"dirty" means, you have changed something in this directory. pls don't touch the klipper or the moonraker direktory. you can fix it with:

```
cd ~/moonraker
git reset --hard
```

**Comment by wuestner** [comment]
`pi@mainsailos:~/moonraker $ git reset --hard
HEAD is now at e2c325a extract_metadata:  support first layer height expressed a                                                                                                                                                           s a percentage`

mainsail still shows "dirty" in the gui
