### ISSUE TITLE
Editing existing Preheat Presets after adding another heater is not possible

### ISSUE THREAD

**Issue by alexhocks** [meteyou/mainsail#182]
**Describe the bug:**\
I start out with two heaters configured (bed and extruder). I then proceed to add a preheat preset (lets say PLA, 215°C extruder and 60°C bed). Then I add another "heater" to the printer.cfg. In my case a temperature_fan for a Voron 2.4 exhaust paired with a thermistor in the build chamber. When I try to edit my old PLA profile, which was created when only two heaters were configured, the window to edit the preset won't open.
When I remove the additional heater from the config again and restart klipper, i can edit my preset again.

**Expected behavior:**\
Every preheat preset should be editable all the time, no mater what configuration it was created on. Heaters missing in a new configuration can be omitted in old presets. New heaters in a for an old configuration should be assigned the default value for that heater from the config.

**Comment by meteyou** [comment]
pls upload your .mainsail.json. you can find it in machine > settings and display hidden files.
