### ISSUE TITLE
Backup of printer.cfg to gdrive/ftpserver [FR]

### ISSUE THREAD

**Issue by kaisertheone** [meteyou/mainsail#186]
in the last few days i lost the printer.cfg file during a corrupted pi system.
i didnt had a recent backup transfered to another system.

i would wish for the possibility to set a server (ftp) maybe a storage in the network or a googledrive document and mainsail uploads the printer.cfg on every boot.

**Comment by zellneralex** [comment]
Use rsnapshot  <https://rsnapshot.org/> as destination you can do everything you want. I have a samba running that connects my NAS.

**Comment by th33xitus** [comment]
How often do you change stuff in your printer.cfg that you need an upload on every boot?
You could use github too. Shell script, cronjob... push it there...
There are so many solutions for backing up files somewhere, i don't think mainsail should be tasked with it.

**Comment by meteyou** [comment]
@kaisertheone mainsail is only execute in your browser. there is no running task on the host/rpi for create a backup or anything else. if i would implement a backup function in mainsail, it should download all data from the rpi to your local pc and then backup it. i don't think this will work well. but you can ask moonraker for implement a backup feature. furthermore there are enough free/opensource tools for linux to set up such a backup system...

**Comment by kaisertheone** [comment]
i think under this circumstances this FR can be closed :)
