### ISSUE TITLE
Temperature of extruder isn't applied when set manually during print start

### ISSUE THREAD

**Issue by DruckiMcDruck** [meteyou/mainsail#190]
**Describe the bug:**\
When starting a print, Mainsail usually heats the bed first and only heats the extruder afterwards. When trying to set the extruder temp manually while the bed hasn't reached its target, the extruder target temperature is applied and shown on the webinterface, but the extruder won't heat until the bed has reached its target temperature. Note the timestamp of the entries in the console at the bottom of the screenshot. I set extruder temp at 21:42:59 and still the extruder temp drops further till the bed reaches its target at around 21:43:30. Then the extruder is heated.

**Expected behavior:**\
If i set the extruder temp while the bed is heating up i expect Mainsail to heat both simultaneously. However Mainsail shows the new extruder target, but won't heat it.

**Screenshots:**\

![image](https://user-images.githubusercontent.com/47270566/106953348-932a9800-6732-11eb-88c1-91f07bb87b7b.png)

**Comment by meteyou** [comment]
thats your start gcode. i think you use M190 (Set bed temperature and WAIT) in your start gcode. is klipper in the WAIT state, it cannot execute any gcode/command. you see the sending command in the console, but klipper will not execute it.

**Comment by DruckiMcDruck** [comment]
Thanks for your hint. I investigated further and it seems like Cura defaults to M190 instead of M104/140. You need to set a specific start code to make cura use M140/104 instead... 

Works now, so closing here as this is intended behaviour and not a bug.
