### ISSUE TITLE
Raspberry Pi temperature color in chart not functioning

### ISSUE THREAD

**Issue by dreedijk** [meteyou/mainsail#197]
When the Pi is added with (according to docs.mainsail.xyz):

[temperature_sensor raspberry_pi]
sensor_type: rpi_temperature
min_temp: 0
max_temp: 85

the chart is displaying a blue line indicating the temperature (default color). When changing this color, the color is not displayed. When going back to the color selection, the color is reset to the default value, but the line is no longer visible in the chart.

<img width="787" alt="Screenshot 2021-02-09 at 10 01 02" src="https://user-images.githubusercontent.com/4368937/107340297-e186c080-6abd-11eb-822f-8ac7182fd03c.png">

You would expect the line in the chart, to display in the selected color.

I previously added:

[temperature_sensor host]
sensor_type: rpi_temperature
min_temp: 0
max_temp: 85

This gave me the option to show/hide the temperature in the chart. With the [temperature_sensor raspberry_pi] option however, this is not an option. Also I have a mix of names (see the screenshot), where the table displays: Raspberry pi and the legend still displays the previous name: host

After a complete restart, I have the correct legend name (still without the color indication) and the option to show/hide the value in the chart. The color is now saved, but still not displayed in the chart.

If you need logfiles, please let me know. I have not added them for privacy reasons.

**Comment by dreedijk** [comment]
Another thing I noticed. I thought I'd then change the heat bed color to at least distinguish between the temperatures in the chart and by changing the Heat bed color, also the Raspberry pi color changed to the same color. So it appears that the colors are linked ...

**Comment by meteyou** [comment]
i fixed this already. will be in the next release -> https://github.com/meteyou/mainsail/commit/6fb8d1614357ba3a086d724d970dc20a2634da64
