### ISSUE TITLE
Connecting to Klipper randomly appears

### ISSUE THREAD

**Issue by orkusmg** [meteyou/mainsail#2]
During some activities (i.e. QGL) I get Connecting to Klipper notification to pop up, the camera feed does still work though, toolhead is moving on it etc. Console does not get updated anymore, F5 fixes it but console is cleared with every F5 (web page refresh).
![2020-04-25_09h22_06](https://user-images.githubusercontent.com/49352823/80273934-f3d27200-86d6-11ea-9218-788ba43bb84c.png)

**Comment by orkusmg** [comment]
Additional info: it does not happen during print.

**Comment by meteyou** [comment]
this is a known bug. the error is reproducible with every command with a execute time over 30-35 seconds. only if the command is pushed by KWC. the response has a timeout.

**Comment by meteyou** [comment]
there was a bug in the klipper-api. Pls update klipper!
