### ISSUE TITLE
Hight CPU usage and unusable on mobile

### ISSUE THREAD

**Issue by SilverWx** [meteyou/mainsail#204]
![image](https://user-images.githubusercontent.com/16896194/108349947-e2b59d00-71e3-11eb-938f-9669dceb0229.png)

I got high CPU usage on my computer, and interface seriously lag on my Galaxy S10.

I use brave webbrowser bassed on chromium both on my pc and my phone.

**Comment by meteyou** [comment]
mainsail is a dynamic gui and data is streamed from moonraker in 200ms intervals! the consumption MUST be higher than with a static website.

**Comment by SilverWx** [comment]
Ok I understand that bu i'm not experiencing this lag it's fluidd on my phone so I am wondering about that

**Comment by meteyou** [comment]
i cannot reduce the update interval, because these are push updated. there is no polling. if you fill out the full bugfix form and upload all data i can reopen this ticket and double check it. with this minimal description, i cannot check anything...

**Comment by meteyou** [comment]
this is the current dev version of mainsail and the current fluidd version of app.fluidd.xyz:

![image](https://user-images.githubusercontent.com/8167632/108404002-a1db7980-721f-11eb-982b-6e687e70cd39.png)

i can't see any difference between the two, unfortunately.

**Comment by SilverWx** [comment]
Thank you a lot for checking that.
I admit I have not using fluidd a long time, I just remember I didn't get problem on my phone but I have to try again.
I'm not at home for now but I will check and get log trying using mainsail on my phone and post it here.

On my phone, at the beginning all work in fluid way at the beginning but after clicking move axis button multiple time it start lagging.

**Comment by meteyou** [comment]
i will try to switch off individual panels to see what the real problem is. i know that the webcam + the tempchart are major performance eating features.

**Comment by TravisWilder** [comment]
I can confirm high cpu with Safari and chrome on Mac
without webcam and tempchart it is better, but it is still to high: 40% for just the dashboard is too much

**Comment by meteyou** [comment]
@TravisWilder we are working on this issue...

**Comment by meteyou** [comment]
new beta release should fix the issue. pls test it
