### ISSUE TITLE
[FR] Use arrows instead all the move buttons.

### ISSUE THREAD

**Issue by simonvez** [meteyou/mainsail#212]
The move commands are not so intuitive. It think it would be much better and look better to have the control pad with arrows like every other printer command interface out there. What do you guys think? 

And I would also like to thank you all for developing this awesome product.

**Comment by meteyou** [comment]
the current movement buttons are DWC like. i used DWC for a long time before. its for me the fastest and best solution, but cross buttons like octoprint are in the backlog for a long time... some day, i will implement it...

**Comment by meteyou** [comment]
@simonvez pls test the new release (v1.4.0). there is an alternative control option.
