### ISSUE TITLE
timeout in [idle_timeout] is ignored

### ISSUE THREAD

**Issue by DasBootU96** [meteyou/mainsail#221]
**Describe the bug:**\
Copy paste from https://github.com/KevinOConnor/klipper/issues/3865 :

When I restart Klipper service and then turn on heater bed only without touching anything else, the timeout in [idle_timeout] is ignored and the heater bed remains on.

If you were to home the printer, the heaters will be automatically turned off after the specified timeout since the last move.

When I restart Klipper service and perform a Home (G28) and then turn on heater bed without touching anything else, the timeout in [idle_timeout] is honored and the heater bed is turned off exactly as expected.

Used a 120 second timeout to test:

``[idle_timeout]``
``timeout: 120``

Can you please confirm behavior, whether or not it is function as designed or bug or if there are workarounds available?

Mr. Klipper himself KevinOConnor says klipper is functioning as designed :-)

**Expected behavior:**\
I turn on the heated bed only for it to heat the chamber, then I sometimes get distracted and forget about it. Expected behavior is for klipper to turn off heaters automatically after the timeout expires without having to 'move' (e.g. home) the printer

**Screenshots:**\

**Logfiles:**\
Please upload your Logfiles here or upload them to [pastebin.com](http://pastebin.com) and paste your log links here.

Turned on printer, set bed temperature to 50 (SET_HEATER_TEMPERATURE HEATER=heater_bed TARGET=50), waited 8, 9 minutes, but bed does not turn off. Then home (G28) the printer and the bed turns of after 120 seconds.

[klippy.log](https://github.com/meteyou/mainsail/files/6093478/klippy.log)
[moonraker.log](https://github.com/meteyou/mainsail/files/6093479/moonraker.log)
[mainsail.cfg.txt](https://github.com/meteyou/mainsail/files/6093480/mainsail.cfg.txt)
[moonraker.conf.txt](https://github.com/meteyou/mainsail/files/6093483/moonraker.conf.txt)
[printer.cfg.txt](https://github.com/meteyou/mainsail/files/6093485/printer.cfg.txt)

**Workaround:** 
Adding this [delayed_gcode ](https://www.klipper3d.org/Command_Templates.html#delayed-gcodes) is a workaround:

``[delayed_gcode my_delayed_gcode]``
``gcode:``
``M119``
``initial_duration: 1``

Instead of M119 as gcode, also tried M117 Hello and M114 without success.

Printer is a Voron V0 cxy with SKR Mini E3 2.0 running Mainsail on Rpi3b+. Behavior has been confirmed by at least one other Voron Discord member (meteyou).

From https://github.com/KevinOConnor/klipper/issues/3865, more users have reported the same issue running Mainsail (or Fluidd)

**Comment by meteyou** [comment]
mainsail ist only a webgui and only read values from Klipper! it does not manipulate Something from Klipper.
