### ISSUE TITLE
PrusaSlice not working Print Host upload

### ISSUE THREAD

**Issue by Foxbiker** [meteyou/mainsail#222]
**Describe the bug:**\
After all updates is not possible send job from PrusaSlice to mainsailos. 

**Expected behavior:**\
[moonraker (2).log](https://github.com/meteyou/mainsail/files/6095075/moonraker.2.log)
[klippy.log](https://github.com/meteyou/mainsail/files/6095076/klippy.log)

**Screenshots:**\
![image](https://user-images.githubusercontent.com/43917956/110201332-d166c480-7e62-11eb-9371-4c1ab52c3817.png)
![image](https://user-images.githubusercontent.com/43917956/110201487-a16bf100-7e63-11eb-999a-8224880019dd.png)

**Logfiles:**\
Please upload your Logfiles here or upload them to [pastebin.com](http://pastebin.com) and paste your log links here.
- klippy.log
- moonraker.log

**Comment by fabe83** [comment]
The behavior is due to a change in the moonraker.
In the moonraker.cfg the line [octoprint_compat] has to be added.
Further details are available here: https://github.com/Arksine/moonraker/blob/master/docs/user_changes.md

**Comment by Foxbiker** [comment]
It help, thank you.
