### ISSUE TITLE
[FR] Customizable Command-Buttons

### ISSUE THREAD

**Issue by DerInternets** [meteyou/mainsail#225]
I quite regularly use klipper commands like "SCREWS_TILT_CALCULATE" or "BED_SCREWS_ADJUST". I usually forget the exact name, so I have to check with the klipper documentation each time before i use it.

It would be great to have the possibility to add custom command buttons in a seperate section on the dash that just execute commands (KLIPPER OR GCODE) that you specify. Pretty much like the current "Home All"-Button.

This would for example allow the user to add a "change filament"-Functionality by just adding a button that executes the gcodes for heating and retraction of a certain length.

**Comment by meteyou** [comment]
you only have to create gcode_macros in Klipper. ever macro will be displayed in the dashboard.
