### ISSUE TITLE
Remote Mode Printer missing from Printers page until browser refresh

### ISSUE THREAD

**Issue by mcarter14777** [meteyou/mainsail#227]
I have been blindly poking my way around remote mode with 2 mainsail setups, and both printers never show up on the printers page and I have to refresh. Then when they do appear does appear, the printer name is not displayed, only the address and port, and the printer status says unknown. They do appear with correct names and status when clicking the ">" on the Printers button. I have changed the hostnames of each printer so they are not duplicates. I also have tried using a different port for moonraker on one printer, but this brings a new problem because http://my.mainsail.xyz seems to default each printer to port 7125 even after editing. I know the docs for remote mode are not done yet but I feel like I should share my experience.

Thanks for your awesome work!
Let me know if you need me to provide any logs!

**Comment by meteyou** [comment]
are both printers on the current Moonraker version? the printer name in settings > interface will be displayed in the printers page. the hostname is only to connect...

**Comment by mcarter14777** [comment]
Both printers are on the latest versions. On the printers page I have seen it display the printer card using the printer name and also the status with temperatures under, but only a couple times. I believe everything is working fine connection wise as I do get the status in the drop-down menu. The issues are most likely with the printers page.

**Comment by meteyou** [comment]
should be fixed
