### ISSUE TITLE
[FR] Controll WLED's / D1mini based on Print status / other events

### ISSUE THREAD

**Issue by itCarl** [meteyou/mainsail#234]
**Led's go blink blink.**

Currently i have about 20 d1mini's around my house that run WLED to controll some leds and Lamps.
(and of course one on my 3D Printer that controlls a light bar)

**So here is my Plug-in Idea / FR:**
if a print fails (may be detected by some spaghetti detector) some defined lights go red or Blink or something.
if a print is done some defined lights go green or something.

**Possible implementation:**
On [Printer status "done|error|etc."](https://github.com/Arksine/moonraker/blob/master/docs/web_api.md#basic-print-status) send request to one of the clients that run wled. These client ips could simply be saved as a list in a file.

[WLED ](https://github.com/Aircoookie/WLED)on Gtithub
[WLED json API ](https://github.com/Aircoookie/WLED/wiki/HTTP-request-API)

**Comment by meteyou** [comment]
it doesn't make sense to implement this in mainsail, because mainsail only runs in your browser. if you turn off your pc, or just close the browser window, mainsail doesn't run anymore and couldn't switch your leds. this would have to be done as a moonraker plugin.
