### ISSUE TITLE
[FR] 3 Column Layout and Minimal Menu

### ISSUE THREAD

**Issue by 11chrisadams11** [meteyou/mainsail#238]
**Describe the solution you'd like**
I think it would be nice to have an option to have a 3 column layout on the dashboard. I would prefer to not have to scroll to see everything while printing.

Also, It would be nice to be able to minimize the side menu to just icons, like Home Assistant does. It gives more screen real estate while still being able to change to the needed pages.

Thanks for the consideration

**Comment by meteyou** [comment]
pls check all open issues the next time. this is already a open FR... https://github.com/meteyou/mainsail/issues/183
