### ISSUE TITLE
[FR] Publish latest mainsail using GitHub Pages

### ISSUE THREAD

**Issue by ayufan** [meteyou/mainsail#239]
**Describe the solution you'd like**
The [fluidd](https://github.com/cadriel/fluidd) publishes an http://app.fluidd.xyz/. The Mainsail could do the same: publish latest release as a regular GitHub Pages web-page allowing to easily use mainsail without installing anything. Just open webpage, put an URL to your Moonraker and start using it.

It would very likely increase adoption of Mainsail as it would require running Moonraker only.

**Comment by meteyou** [comment]
since many releases http://my.mainsail.xyz is available.

**Comment by ayufan** [comment]
Oh. This is awesome. Why I didn't see it before? Should we make it prominent in `README.md`?

**Comment by meteyou** [comment]
Because the docs guy, is finishing the new docs ATM. And no... This was my first idea, but if you use a HTTPS webapp, you have to use a SSL secure websocket (Moonraker). You can open my.mainsail.xyz with HTTPS, but you have to change your websocket with HTTPS proxy or something else on your printer.

**Comment by ayufan** [comment]
So, from `https://` we cannot downgrade to `ws://`? Is that correct @meteyou ?

About `https://` => When I use `https://my.mainsail.xyz` I see the invalid certificate.

**Comment by meteyou** [comment]
All modern browsers blocking all connections to none secure sockets.

Thx for the info. I will fix it.

**Comment by meteyou** [comment]
https://github.com/meteyou/mainsail/commit/39c2b51faaa43047b1de43ea473cf4c8ede15fdd

**Comment by ayufan** [comment]
@meteyou 

> Thx for the info. I will fix it.

Did you had opportunity to fix HTTPS certificate?
