### ISSUE TITLE
Error with IPv6 and Authorization

### ISSUE THREAD

**Issue by manoukianv** [meteyou/mainsail#25]
Hello,

I follow the installation guide in the REDME.md and i have an issue with the "hostname" resolver.
When i call the page with the IP number http://myip/ it works, but with my hostname http://klipper.local/, it doesn't work.

In the log, i have an error 401 and the specified IP in the log is a IPv6 : 
```
2020-06-07 23:22:19,202 [web.py:log_exception()] - 401 GET /websocket (2a01:cb05:xxxx:xxx:xxxxx:49fe:51ef:8bdf): Unauthorized
2020-06-07 23:22:19,217 [web.py:log_request()] - 401 GET /websocket (2a01:cb05:xxxx:xxx:xxxx:49fe:51ef:8bdf) 16.85ms
```

I update the nginx config like that : 
    listen 80 default_server;
    #listen [::]:80 default_server;
And it works now with that config. Nginx seems to reject IPv6, and the log have successful call with the IPv4 address.

I'm bad in networks, not sure if this patch is the good one. But it can be helpful.
Vincent

**Comment by meteyou** [comment]
This problem will be solved in Moonraker.

**Comment by grigorig** [comment]
I am still seeing this exact problem. Looks like nothing was solved after all?

**Comment by meteyou** [comment]
@grigorig just add your ipv6 range as trusted client in your moonraker.conf or disable ipv6 in nginx (like the example above).

**Comment by grigorig** [comment]
The IPv6 prefix may change, so this won't work reliably. Moonraker seems to support user-based authorization, I wonder why this isn't used by default? This seems to be a far superior and more secure solution (your local network usually cannot be trusted - that is a really basic and inadequate security model). I cannot find any documentation on how to actually use user-based authorization from the Mainsail UI, though.

**Comment by meteyou** [comment]
> The IPv6 prefix may change, so this won't work reliably. Moonraker seems to support user-based authorization, I wonder why this isn't used by default? This seems to be a far superior and more secure solution (your local network usually cannot be trusted - that is a really basic and inadequate security model). I cannot find any documentation on how to actually use user-based authorization from the Mainsail UI, though.

Because it's not build in. Too many users think, that this feature is to make there printers public!
