### ISSUE TITLE
[FR]Automatic M73 Percentage Update

### ISSUE THREAD

**Issue by GeoCyberwolf** [meteyou/mainsail#268]
**Is your feature request related to a problem? Please describe.**
Print % completed doesnt update on printer display

**Describe the solution you'd like**
It would make sense for Mainsail to automatically send M73 P updates as the percent increases. Typing these manually updates the display.

**Comment by meteyou** [comment]
this is not possible for mainsail. it is only a webapp and every time, you close your browser window, it cannot send the command. old use your slicer for it.
