### ISSUE TITLE
File editor has the content of the wrong file when using browser back button

### ISSUE THREAD

**Issue by t3chguy** [meteyou/mainsail#284]
**Describe the bug:**
1. Start on the dashboard (other views may work too)
1. Go to Settings > Machine
1. Open a file, e.g `kiauh_macros.cfg`
1. Use the browser back button, you'll be back on the dashboard
1. Go to Settings > Machine
1. Open a *different* file, e.g `printer.cfg`
1. Observe you are shown the name of the file you selected but the contents of the other file.

**Expected behavior:**
I expect the final step to show me the contents of the file I selected

**Screenshots:**
![image](https://user-images.githubusercontent.com/2403652/118904048-f2db3680-b910-11eb-8bd7-47a0dcf5f5b3.png)

Mainsail version v1.6.0

**Comment by meteyou** [comment]
this bug is fixed with the new editor
