### ISSUE TITLE
File editor destroys hard and symbolic links

### ISSUE THREAD

**Issue by adolson** [meteyou/mainsail#287]
**Describe the bug:**\
If you edit a hard or symbolic linked file and then save the file, the link is destroyed and a new file is written.

**Expected behavior:**\
The changes should be saved to the linked file, preserving the link.

**Comment by meteyou** [comment]
Pls make a bugreport to Moonraker. In mainsail, I only get the filename and the content from Moonraker. Only Moonraker write and read the file.
