### ISSUE TITLE
"Error Configuring Printer"

### ISSUE THREAD

**Issue by Nickbuddypal** [meteyou/mainsail#290]
I have an SKR Mini E3 v2 hooked up to a raspberry Pi 4, installed with MainsailOS through the .img file listed on the website. When I go to connect it simply states "Error Configuring Printer " under Klippy-State: Error. I have had this happen with a separate Raspberry Pi Zero and SKR Mini E3 V1.2 on another printer which was working and then suddenly would no longer connect. I made sure that I flashed the firmware correctly, including the !PA14 GPIO section. I have tried switching the pis over with no success.

**Logfiles:**\
moonraker.log https://pastebin.com/FS8MK5xp
klippy.log https://pastebin.com/JmWDY8B8

**Comment by meteyou** [comment]
This issue tracker is only for mainsail issues. You have a Klipper config problem. Pls join our discord for help.

Ah... And you klippy.log is also the moonraker.log... pls upload it again and post the right link in the discord.
