### ISSUE TITLE
[FR] install deps, config for resonance measurement

### ISSUE THREAD

**Issue by blalor** [meteyou/mainsail#297]
**Is your feature request related to a problem? Please describe.**

When following the guide to performance [resonance measurements](https://www.klipper3d.org/Measuring_Resonances.html) I was surprised that SPI was not enabled, and that numpy and matplotlib were not already installed.

**Describe the solution you'd like**

Preinstall the dependencies and enable SPI.

**Describe alternatives you've considered**

Installing them manually on the system is certainly doable, but numpy in particular is a big dependency and slow to build.

**Additional context**

<img width="718" alt="image" src="https://user-images.githubusercontent.com/109915/122684832-e418c580-d1d5-11eb-9c25-8219fcdfa612.png">

I suspect that installing `python-numpy` before creating the virtualenv will make for much faster installation, although the venv may need the flag for including site packages.

**Comment by meteyou** [comment]
mainsail is just the webinterface. the webinterface will only be execute in your browser, so there are no possibility to "install" this libs.

**Comment by blalor** [comment]
Bah. I knew that! The "recommended" way to install is [via mainsailos](https://docs.mainsail.xyz/setup/mainsail-os) and I just clicked the "mainsail on github" link. Sorry!
