### ISSUE TITLE
Mainsailos looses wifi connection if webcam resolution is higher then standard.

### ISSUE THREAD

**Issue by xp1ratex** [meteyou/mainsail#313]
**Describe the bug:**\
If i switch webcam resolution to: camera_usb_options="-r 1920x1080 -f 15" in  /boot/mainsail.txt mainsailos starts to lag after a while and looses wifi connectivity, i have to kick it out of the acesspoint for it to come back. If i switch back to auto settings everything seems to work (its been working for 24h atleast)

**Expected behavior:**\
Running the same webcam configuration on octoprint with the same webcam (logitech HD PRO c920) on my other machine and dont have any issues with the wifi.

**Screenshots:**\

![TOP](https://user-images.githubusercontent.com/65679573/126825938-7edb88db-c039-4708-9aee-76409b617bfd.JPG)
![free](https://user-images.githubusercontent.com/65679573/126826036-bbf54082-13e2-4999-b3d0-08397db5e376.JPG)

**Logfiles:**\
Please upload your Logfiles here or upload them to [pastebin.com](http://pastebin.com) and paste your log links here.
- klippy.log
[klippy (1).log](https://github.com/meteyou/mainsail/files/6870584/klippy.1.log)
- moonraker.log
[moonraker (1).log](https://github.com/meteyou/mainsail/files/6870587/moonraker.1.log)

**Comment by meteyou** [comment]
mainsail is just the webinterface... this is a raspberry issue. the wifi chip go in sleep mode.

**Comment by xp1ratex** [comment]
The wifi sleepmode is off, something with the mainsailos is diffrent to the octopi since it doesnt loose wifi if i enable higher cam resolution.
![brcmfmac](https://user-images.githubusercontent.com/65679573/127630217-d2de16ec-8ab1-453a-9133-082d514a8c27.JPG)
![iwconfig](https://user-images.githubusercontent.com/65679573/127630267-953a44c4-d704-4f3b-9609-3f8bc58d131e.JPG)

**Comment by ichbaum** [comment]
I have the same problem. The webinterface stopped working. But only now and than.
No problems with the standard resolution.
I never had that problem with octoprint.

**Comment by meteyou** [comment]
this is a network issus. octoprint and mainsail are just webinterfaces...
