### ISSUE TITLE
Web UI in Safari (Mac OS)

### ISSUE THREAD

**Issue by TjardF** [meteyou/mainsail#316]
Hi,
I recently installed Mainsail and tried to access it via Safari, it only loads a Black window.
With Chrome everything works fine.
Is this a known issue? is there any way to solve it or will it be fixed in future version?
![Bildschirmfoto 2021-08-01 um 11 11 16](https://user-images.githubusercontent.com/37928929/127765704-800e9dd2-339d-4d98-af10-9e18d6afbcfe.png)

**Comment by meteyou** [comment]
pls more informations... browser version numbers and mainsail version number.

i changed some things for older safari support. this should be in the next beta release (will be released in the next days)

**Comment by meteyou** [comment]
@TjardF can you check this again?

**Comment by TjardF** [comment]
Hi,
I tried again with 1.6, now everything works fine
OS X 10.15.7
Safari 13.1.3
