### ISSUE TITLE
[FR] Possibility to organize MACROS

### ISSUE THREAD

**Issue by kakou-fr** [meteyou/mainsail#33]
Hi,

I just installed Mainsail today, looks like it works, but i as i have a lot of MACROS, i have this rendering.

Could it be possible to organize the MACROS ? 

Select the one we need on each line, and  the order of the MACROS (not only alphabetic ordering) ?

Maybe also select the color of each macro (not only blue)

![image](https://user-images.githubusercontent.com/29911575/89734045-d9d85780-da59-11ea-8b61-c5f637ed2e35.png)

**Comment by meteyou** [comment]
You can hide macros in settings > interface. In backlog there will be a switch for "only during print", "only in idle mode" and "both". More is not planned at the moment...

**Comment by meteyou** [comment]
@kakou-fr do you try to hide the unimportant macros on the dashboard?
