### ISSUE TITLE
Temp chart not displaying data or updating

### ISSUE THREAD

**Issue by bill-orange** [meteyou/mainsail#331]
**Describe the bug:: Operation seems normal but the chart has no data as shown.  Running: v2.0.0-beta4
v0.9.1-682-g1aa4becc

**Expected behavior:  Temp value displays in chart

**Screenshots: 
![temp chart](https://user-images.githubusercontent.com/18121312/129813273-02872f76-13bb-42cb-9737-f857330bb715.png)

**Logfiles:

[Downloads.zip](https://github.com/meteyou/mainsail/files/7003512/Downloads.zip)

**Comment by meteyou** [comment]
is this the first load of mainsail? atm, i'm working on it, if a sensor is not in the moonraker history, it is not included in the chart. if you refresh one time and moonraker provide history data for the sensor it should work...

**Comment by bill-orange** [comment]
Thanks.  Refresh corrected the problem.
