### ISSUE TITLE
[FeatureRequest] Babysteps allways available

### ISSUE THREAD

**Issue by Stephan3** [meteyou/mainsail#34]
Dear Meteyou.

Please consider making babystepbuttons visible at any time.
I step the nozzle allways to paper b4 starting a print for safety reasons.

Thanks.
Stephan

**Comment by robthide37** [comment]
does this mean your leaving the dwc dev

**Comment by Stephan3** [comment]
@robthide37 That means that i try another webinterface. :)

**Comment by meteyou** [comment]
Use PAUSE gcode at printstart or gcode buttons.
