### ISSUE TITLE
Safari edit Configs

### ISSUE THREAD

**Issue by TjardF** [meteyou/mainsail#342]
**Describe the bug:**\
After clicking on some files, the download in der right corner appears but the pop up didn't open up. Chrome works

Mac OS 10.15.7 (19H1030)
Mainsail v0.9.1-743-g95047784
**Expected behavior:**\
That the Text editor opens, like in Chrome

**Screenshots:**\
![Bildschirmfoto 2021-08-29 um 20 37 21 PM](https://user-images.githubusercontent.com/37928929/131261624-013850a2-5d78-4152-8cdf-91c37403b795.png)
![Bildschirmfoto 2021-08-29 um 20 37 27 PM](https://user-images.githubusercontent.com/37928929/131261628-3b79758a-670e-4429-b2b3-fc2c77901998.png)

**Logfiles:**\
[klippy-2.log](https://github.com/meteyou/mainsail/files/7073034/klippy-2.log)
[moonraker.log](https://github.com/meteyou/mainsail/files/7073035/moonraker.log)

**Comment by meteyou** [comment]
do you use safari 14.0? i checked it on big sur with safari 14.1 and it work fine. a friend also reported this bug. seens to be a safari 14.0 bug with BLOB. pls try to update your safari.

**Comment by B0rax** [comment]
for context, I had the same problem. You can update Safari to 14.1 on Catalina. It's not very obvious how, but there is an update available.

Go to System Settings -> Software-update
It should tell you that there are further updates available (not the Mac OS update itself):
![Bildschirmfoto 2021-09-03 um 07 51 23](https://user-images.githubusercontent.com/10982690/131957130-f99109b6-336f-41d5-a86f-20d95d4c3d3f.png)

click on "more information" and follow the instructions.

Then everything should be working.

**Comment by meteyou** [comment]
@TjardF did you tested the tip from B0rax?

**Comment by retroneo** [comment]
2.0 and 2.0.1 work fine on Catalina for me.

**Comment by TjardF** [comment]
@B0rax Trick worked out perfectly, thanks
