### ISSUE TITLE
Bed Mesh Issues

### ISSUE THREAD

**Issue by Jestinweber** [meteyou/mainsail#346]
I'm currently trying to get Bed Mesh to work with no luck so far. When I try BED_MESH_CALIBRATE I get an error saying "Already in a manual Z Probe. Use ABORT to abort it."
I cant find anywhere how to resolve my issue so I figured I'd try my luck here. I look forward to resolving this issue!

[klippy (9).log](https://github.com/meteyou/mainsail/files/7102204/klippy.9.log)
[moonraker (2).log](https://github.com/meteyou/mainsail/files/7102205/moonraker.2.log)
![Mainsail_and_Klipper](https://user-images.githubusercontent.com/90010446/131926158-760198ec-cf42-4d99-87cf-90daf90a384d.png)

**Comment by meteyou** [comment]
this is a klipper config error. this have nothing todo with mainsail. if you need klipper help, feel free to join our discord server and ask in the klipper channel.

**Comment by Jestinweber** [comment]
will do. thanks a bunch!
