### ISSUE TITLE
Version mismatch...did I screw up somehow?

### ISSUE THREAD

**Issue by AaronHerrick** [meteyou/mainsail#359]
**Describe the bug:**\
The Mainsail version in the lower left does not update from 1.6.0 to 2.0.1

**Expected behavior:**\
I expect it to update the version

**Screenshots:**\
![image](https://user-images.githubusercontent.com/43390476/133941132-4477d834-6cd0-4265-a9fd-f28fdbf4c9c9.png)

**Logfiles:**\
Please upload your Logfiles here or upload them to [pastebin.com](http://pastebin.com) and paste your log links here.
- klippy.log
- moonraker.log
I can't do that for ... reasons.  but let me know if you really need something from them

**Comment by AaronHerrick** [comment]
closing, the value did update a few hours later.  Could it be because I had 2 different computers viewing the website?

**Comment by meteyou** [comment]
yep. when you use 2 pcs (2 differnt browsers), your browser will cache mainsail. on the pc/browser you update mainsail, ther will be a "force reload" and it will update the static files. on the other pc, you have to reload without cache. for example

cmd+shift+r on mac
ctrl+shift-F5 on pc
