### ISSUE TITLE
Ability to edit config files and macros /  programs

### ISSUE THREAD

**Issue by changedsoul** [meteyou/mainsail#36]
Im coming from DWC2-for-klipper and find this to be much more responsive, but I miss the ability to adjust my config file without having to ssh into the pi to change it. 
Is this possible with this interface?

**Comment by meteyou** [comment]
config editor is already in the master branch -> [Commit](https://github.com/meteyou/mainsail/commit/29d5b81b470f0f54bc98bfd051658d3a48df91ba)

we are working every day on new features. pls dont create so basic feature requests! mainsail is only less months old!! we are not finished to implement all basic features.
