### ISSUE TITLE
Mainsail title tag for GCODE filename not working properly

### ISSUE THREAD

**Issue by translucentfocus** [meteyou/mainsail#39]
![image](https://user-images.githubusercontent.com/26986716/90323169-19ec7e00-df23-11ea-83e5-a1575c6a4e2e.png)

There's an issue located [somewhere with this code](https://github.com/meteyou/mainsail/blob/9bdcec01cab9bdb2906c99452b3cfa02df93c85d/src/store/getters.js#L253)

My GCODE filename for this test was V350_FilamentCard.gcode if that helps.

I'd love to contribute & fix the code myself, but don't know of a good way to setup a test environment to test changes.

**Comment by meteyou** [comment]
is the gcode file in the root directory or in a sub directory?

**Comment by translucentfocus** [comment]
It is in the root directory

![image](https://user-images.githubusercontent.com/26986716/90521883-a8821a80-e130-11ea-80aa-64870b10ae13.png)
