### ISSUE TITLE
Where are the RasPi Images?

### ISSUE THREAD

**Issue by altimmons** [meteyou/mainsail#402]
**Describe the bug:**\
Images for raspi are unavailable.  Reviewing Tutorials online show they were at one time in releases. 
Documentation goes into great detail on how to flash, without anything TO flash

**Expected behavior:**\
The Recommended Install method of the Image should be available, or some such

**Comment by altimmons** [comment]
found it, via discord-
some hint to check https://github.com/raymondh2/MainsailOS/releases would be ideal, via ReadTheDocs or in README.md

**Comment by meteyou** [comment]
we use `Jekyll` docs and it is available via this url: [https://docs.mainsail.xyz](https://docs.mainsail.xyz). this URL is linked multiple times in [https://github.com/meteyou/mainsail/blob/develop/README.md](https://github.com/meteyou/mainsail/blob/develop/README.md)
