### ISSUE TITLE
[FR] .3mf / .stl Model viewer using THREE.JS

### ISSUE THREAD

**Issue by itCarl** [meteyou/mainsail#403]
it would be really nice to be able to view the current printing Model in 3D instead of just seeing a Thumbnail.

could be implemented with this [nice little javascript library (THREE.JS)](https://threejs.org/
)

Example:
https://threejs.org/examples/webgl_loader_3mf

or another possibility that occurred to me while I was writing.

A 3D virtual version of the printer.
This 3D version would then make exactly the same movements as the real printer in real life. This would ensure a better monitoring of the printing process and also for the error search this would be practical... then one would need e.g. no camera to acquire...

**Comment by meteyou** [comment]
.3mf or .stl are not supported by klipper, but a gcode 3d viewer we are already build in and will be part of the next release. pls check this FR: https://github.com/meteyou/mainsail/issues/315
