### ISSUE TITLE
Great Job!!

### ISSUE THREAD

**Issue by changedsoul** [meteyou/mainsail#41]
I just want to apologize for any misunderstandings before while this project in chaos last week. Poor timing on my part to try it out, I had no idea it was in its infancy stage.
I noticed it got updated and followed the current install instructions and had zero issue.
Just wanted to say, Great Job. It looks great, seems to work great.
Thanks for all the effort everyone had in this.

I know this is not an issue, but I wasnt sure how to say thanks for a great project.

**Comment by meteyou** [comment]
Thank you very much!
