### ISSUE TITLE
Temp Graph doesn't span entire X axis

### ISSUE THREAD

**Issue by weasel0x00** [meteyou/mainsail#44]
For some reason my temp graph gets truncated on the oldest half of the X-axis... It seems to work fine after a restart.  I notice it when I finish one print and start a new one afterwards. The print in the image below has been running for over 3 hours.  Hrmm, actually, I just noticed that if I refresh the entire page in my browser it also seems to fix itself for a short while, then it moves back to half full again.

![image](https://user-images.githubusercontent.com/1728630/90350245-b84b1300-dff9-11ea-9fd0-e88fe1cf0636.png)

**Comment by meteyou** [comment]
in the next version i have to redo the complete temp chart anyway. this was a bug, because the timing for temp chart a closer in the current version of moonraker.

**Comment by meteyou** [comment]
@weasel0x00 pls recheck this issue with the current version

**Comment by paulhew69** [comment]
Looks good to me.
