### ISSUE TITLE
Cannot select file to print in G-Code Files

### ISSUE THREAD

**Issue by paulhew69** [meteyou/mainsail#50]
Not a show stopper
When in the G-Code Files tab, If you Right-Click a file, you have the options for Print, Download, Rename
You cannot select print.

**Comment by meteyou** [comment]
can you report more informations like browser, browser version, mainsail version, current state of klipper?

**Comment by paulhew69** [comment]
Just updated to v0.2.0.
Just right clicked a file, selected print and it asks if I would like to download it.

**Comment by paulhew69** [comment]
FireFox 80.0 (64-bit), Ubuntu

**Comment by meteyou** [comment]
i cannot reconstruct this error, anyone else have problems with this?

**Comment by paulhew69** [comment]
A little video showing the issue
https://www.dropbox.com/s/5u65o1yosrzvfkj/VID_20200902_084230.mp4?dl=0

**Comment by sebadue** [comment]
Yes, I can confirm that behavior in 0.21:
https://www.dropbox.com/s/dypkl1tm57xqqh7/MainSail.mp4?dl=0

That seems to be independent from the browser:
Firefox 80.0.1 and Safari 13.1.2 are both affected.

**Comment by sebadue** [comment]
Seems I have found the code line to blame:

https://github.com/meteyou/mainsail/blob/25a7e8a33b2ea7d4126ebfa6ed29d7f992edcd6b/src/pages/Files.vue#L152

Calls downloadFile on click.

**Comment by meteyou** [comment]
should be fixed in the the current version. pls update and try it again...

**Comment by sebadue** [comment]
Thanks, the issue is solved with 0.2.2!

**Comment by paulhew69** [comment]
Can confirm issue is fixed - Thank you.
