### ISSUE TITLE
Console options - enhancement

### ISSUE THREAD

**Issue by paulhew69** [meteyou/mainsail#51]
Could there be a way of disabling the annoying temp messages in the console, please

**Comment by meteyou** [comment]
I don't know what you mean. Can you give me examples?

**Comment by Mechotronic** [comment]
He means the B messages that are received for certain commands. 
![image](https://user-images.githubusercontent.com/29634711/91931639-06c30780-ecb2-11ea-9315-a11d5a7a936a.png)

**Comment by meteyou** [comment]
at the moment, there is no index... its the question, if klipper should not send this values

**Comment by rafaljot** [comment]
maybe some regexp patterns to filter out unwanted messages ?

**Comment by kakou-fr** [comment]
ability to send a command directly from the console panel in the dashboard will be really well.

**Comment by jwramseier** [comment]
![image](https://user-images.githubusercontent.com/30188977/99339892-9194b680-284c-11eb-8e8b-e0019f967b4f.png)
OctoPrint has this capability

![image](https://user-images.githubusercontent.com/30188977/99339984-ba1cb080-284c-11eb-8585-215788db1173.png)

**Comment by zbrozek** [comment]
I would also love to have a text entry box to send commands from the main page!

**Comment by jperrin72** [comment]
That is a great idea ! I would love to see this feature implemented. All the temperature lines make troubleshooting difficult when you have to go through console output.

**Comment by meteyou** [comment]
i added it -> https://github.com/meteyou/mainsail/commit/3c217e1161e093df90f8467067e932a428d44f2a

will be in the next release
