### ISSUE TITLE
Retract and Extrude buttons do not work

### ISSUE THREAD

**Issue by paulhew69** [meteyou/mainsail#52]
The 'Retract' and 'Extrude' buttons are always greyed out so cannot be used.
I have checked that I have 'min_extrude_temp:' in my printer.cfg

Regards
Paul

![image](https://user-images.githubusercontent.com/61477100/91939430-b8335e80-eced-11ea-87ad-8b6e21169550.png)

**Comment by meteyou** [comment]
update to V0.2.1...

**Comment by paulhew69** [comment]
Morning, that was the first I did this morning. Must remember to put more info on an 'issue' for you.
![image](https://user-images.githubusercontent.com/61477100/91943237-2844e300-ecf4-11ea-9fff-a9c5650aac0a.png)

**Comment by meteyou** [comment]
pls send me your printer.cfg... i cannot reconstruct this error...

**Comment by paulhew69** [comment]
As requested,

[printer (copy).txt](https://github.com/meteyou/mainsail/files/5170921/printer.copy.txt)

Regards.

**Comment by meteyou** [comment]
ok. i cannot find an issue in your config. does the problem still exist with and without min_extrude_temp in V0.2.2? has anyone else this problem?

**Comment by paulhew69** [comment]
I am upgrading from octo to Mainsail on my voron. Will let you know.

Regards,
Paul Hewson
Network Specialist
________________________________

**Comment by paulhew69** [comment]
Finished the upgrade, took the temp to 200 and the buttons do not work on my Voron.
Commented out the min_extrude_temp and still no buttons.

**Comment by paulhew69** [comment]
I have just worked out what the issue is. You have to keep refreshing the page.
Testing process. 
Nozzle at room temp refresh, buttons greyed out.
Nozzle @ 200, buttons greyed out. refresh the page and the buttons are able to be used.

So to make it work I have to remember to refresh the screen.
Videos to show the issue.
https://www.dropbox.com/sh/fplyck9l1bp2978/AADeVoJf5VUs3SjkqiN1WzoWa?dl=0

Browser : FireFox 80.0.1 (64-bit) running on Ubuntu.
Regards,

Paul

**Comment by meteyou** [comment]
should be fixed in the next version.
