### ISSUE TITLE
0.2.2: Unable to delete a gcode file

### ISSUE THREAD

**Issue by theopensourcerer** [meteyou/mainsail#55]
Right click on a file in the gcode files screen and choose the delete option. In the javascript console I get a bad request 400 error.  

![Screenshot from 2020-09-05 16-44-48](https://user-images.githubusercontent.com/3414988/92308674-42eab680-ef97-11ea-8874-611b6644c4d4.png)

I'm using Firefox 80.0.1 on Ubuntu 18.04

**Comment by theopensourcerer** [comment]
I should add, before I checked the javascript console, I checked permissions on the directory and files on my RPi. The sdcard dir is 755 pi:pi and the files are all 644 pi:pi.

I wasn't sure if the mainsail process is running under nginx (www-data) so I made the sdcard directory 775 pi:www-data and the files 664 pi:www-data but they were still not able to be deleted.

Hope that helps.

**Comment by paulhew69** [comment]
All good here, works fine. Deletes the file, no issues.

**Comment by th33xitus** [comment]
Solution: Your filename contains a `%`. Rename that file so that there is no `%` and you can delete that file.

I suspected that the`%` will cause the issue and therefore i quickly tested it myself and could confirm my assumption.

**Comment by theopensourcerer** [comment]
@meteyou Thanks for the swift fix!
