### ISSUE TITLE
firefox

### ISSUE THREAD

**Issue by Coffee0297** [meteyou/mainsail#6]
So ive tested this the day it came out, and firefox wuld not let it connect. but in google chrome from same pc workd fine. has this been fixd? ive mentioned it in voron chat the day of announcement.
kind regards Tonny

**Comment by meteyou** [comment]
yes, i fixed the problem in V0.0.9. pls try it again and make a report!

**Comment by Coffee0297** [comment]
Awesome! Ill check back soon

Kind regards Tonny
