### ISSUE TITLE
Full Screen web app on iOS.

### ISSUE THREAD

**Issue by LazaroFilm** [meteyou/mainsail#60]
It would be great if Mainsail was optimized to work as an iOS web app. that would allow for fullscreen option and a pretty icon and all. 
http://www.onlywebpro.com/2015/07/19/optimizing-full-screen-mobile-web-app-for-ios/

**Comment by meteyou** [comment]
thanks a lot for the tip. i will do it once and therefore i leave this issue open as a reminder.

**Comment by marqueeeeeee** [comment]
I was about to open an issue for this, i think PWA is the way achieve this. I’ll try to tinker with the source and file a PR if i am able to do it.

**Comment by LazaroFilm** [comment]
I'd love to help too. But I'm still learning JavaCript and React right now. Not quite there yet... Some day maybe... Looking forward to it. In the meantime I'm using my old Octoprint Webapp link that was linking to my printer's IP, so I have an Octoprint icon on the phone, but when I tap it it opens Mainsail in full screen.

**Comment by meteyou** [comment]
feel free to make a PR...

**Comment by translucentfocus** [comment]
I have a PR in for [the icon issue](https://github.com/meteyou/mainsail/pull/80), but not the iOS web app issue.

**Comment by translucentfocus** [comment]
> 
> 
> I'd love to help too. But I'm still learning JavaCript and React right now. Not quite there yet... Some day maybe... Looking forward to it. In the meantime I'm using my old Octoprint Webapp link that was linking to my printer's IP, so I have an Octoprint icon on the phone, but when I tap it it opens Mainsail in full screen.

Are you willing to test? I don't have an iOS device but have made a patch located here:  https://github.com/translucentfocus/mainsail/releases/tag/v1.0

If for some reason it doesn't break mainsail, it's easy to revert by running
`cd ~/mainsail`
`wget -q -O mainsail.zip https://github.com/meteyou/mainsail/releases/download/v0.2.2/mainsail-beta-0.2.2.zip && unzip mainsail.zip && rm mainsail.zip`

**Comment by LazaroFilm** [comment]
> Are you willing to test? 

Yes! I installed your branch but don't see a difference in the "Add to Home Screen" behavior. 
I made a [video](https://youtu.be/Ub6AcyskINw) showing it

**Comment by translucentfocus** [comment]
> 
> 
> > Are you willing to test?
> 
> Yes! I installed your branch but don't see a difference in the "Add to Home Screen" behavior.
> I made a [video](https://youtu.be/Ub6AcyskINw) showing it

Awesome! Thanks for trying it... sorry it didn't work... I'm working on a new one to test, but there's still some issues with with it right now.

**Comment by LazaroFilm** [comment]
This is now 100% working since #80 both for the home screen icon and the full screen mode! Thanks!
