### ISSUE TITLE
Selectable temps on the graph

### ISSUE THREAD

**Issue by paulhew69** [meteyou/mainsail#61]
Am I wrong in thinking in the earlier versions of MainSail, you could select what temps were displayed on the graph, by clicking them.
Does not seem to work anymore if it was there. Could it be re-implemented again, please?

**Comment by meteyou** [comment]
it will come again. it's just a bit more complicated with the new temp data synchronization.

**Comment by witem** [comment]
@meteyou maybe you need helps with it? I can try to implement it

**Comment by meteyou** [comment]
@witem thx for your help. i already solved it on my locally branch, but its only the first try. i have to test it a little bit more.

**Comment by witem** [comment]
@meteyou okay, you have some roadmap xto improve this project? I can try to help with some other features or bugs
