### ISSUE TITLE
API key not valid

### ISSUE THREAD

**Issue by Gilabite** [meteyou/mainsail#68]
Hello, just installed mainsail on a new coreXY build and everything is going good so far except for uploading a file from cura. Is cura supported for uploading gcode files yet? It wants a valid API key and wont just take anything I put in there like mainsails docs state. Is there a special port it needs or is 80 fine? Thank you.

**Comment by meteyou** [comment]
the fileupload goes to moonraker and not to mainsail. mainsail is only the webinterface! i think cura does not work at the moment, but you can ask in the moonraker project.
