### ISSUE TITLE
Height map calibration

### ISSUE THREAD

**Issue by krpepe** [meteyou/mainsail#74]
Hello.

Thank you for the wonderful GUI for klipper. I have one question about calibrate in height map. I have a custom probe for my Z axis which requires a retract prior to probing. If I run my Bed mesh macro in console everything is fine but if I use calibrate in height map it tells me the probe is triggered. What code is the calibrate button using and can it be modified? What am I doing wrong. Please help.

Thank you in advance,
Kevin

**Comment by meteyou** [comment]
you can use a macro with rename_existing attribute like this:

`
#
#	BED_MESH_CALIBRATE - Bed Mesh Leveling
#

[gcode_macro BED_MESH_CALIBRATE]
rename_existing: BASE_BED_MESH_CALIBRATE
gcode:
	BED_MESH_CLEAR
	QUAD_GANTRY_LEVEL
	G1 X125 Y125 Z5 F6000
	BASE_BED_MESH_CALIBRATE
`

**Comment by krpepe** [comment]
@meteyou Thank you, I will give that a try!

**Comment by krpepe** [comment]
@meteyou Unfortunately that didn't correct it.

**Comment by meteyou** [comment]
then I cannot help you. the button in heightmap only execute "BED_MESH_CALIBRATE". with the macro example, you can modify this command. if it doesn't work, you have a klipper problem, or a problem with your custom probe!

**Comment by krpepe** [comment]
@meteyou Ok thank you! I know it isn't my probe because if I use the bed mesh macro listed on the on the dashboard it works flawlessly. The only time I have an issue is with calibrate under height map and z-tilt on the dashboard as well. My z-tilt macro works from the dashboard as well. Ill play around with it and if worse comes to worst I go back to octoprint. Thank you for your Time!! Have a great day!

**Comment by meteyou** [comment]
But why you cannot use rename_existing with your macro?

**Comment by krpepe** [comment]
@meteyou I tried it and it didn't correct the issue.

**Comment by meteyou** [comment]
Thx for no information! What do you try correctly? What's is your dashboard macro? What is the correct issue? No informations = no help!

**Comment by krpepe** [comment]
@meteyou this is what I did
[gcode_macro BED_MESH_CALIBRATE]
rename_existing: BASE_BED_MESH_CALIBRATE
gcode:
   pin_release
	BED_MESH_CLEAR
	G4 P500
	BASE_BED_MESH_CALIBRATE
	pin_retract

**Comment by meteyou** [comment]
And how look your dashboard macro? Where is you log file?

**Comment by krpepe** [comment]
@meteyou the information is as follows
![Mainsail Dashboard](https://user-images.githubusercontent.com/26741528/93670264-c6a8a680-fa5f-11ea-8d4c-cf08bca2c56d.png)

**Comment by meteyou** [comment]
Can you show me the content of this macro! I know how a dashboard macro button looks like! Pls send me your config + a klipper log with the error!

**Comment by krpepe** [comment]
@meteyou If i use my bed mesh macro on the dashboard it does the pin_retract macro if I use Calibrate under the height map it ignores it and give me the probe triggered error. Same occurs with Z-TILT by the HOME ALL button. If I use that button it it gives the probe triggered error if I use my Macro it works fine.

here is my entire config

 I will post the klipper log shortly

[stepper_x]
step_pin: ar54
dir_pin: !ar55
#enable_pin: multi_pin:controller_fan
enable_pin: !ar38
step_distance: .0125
endstop_pin: ^!ar3
position_min: 0
position_endstop: 0
position_max: 200
homing_speed: 30
homing_retract_dist: 2
second_homing_speed: 1
homing_positive_dir: false

[tmc2130 stepper_x]
cs_pin: ar53 
microsteps: 16
interpolate: True
run_current: .8
hold_current: .1
sense_resistor: 0.110
stealthchop_threshold: 200
#driver_IHOLDDELAY: 8
#driver_TPOWERDOWN: 0
#driver_TBL: 1
#driver_TOFF: 4
#driver_HEND: 7
#driver_HSTRT: 0
#driver_PWM_AUTOSCALE: True
#driver_PWM_FREQ: 1
#driver_PWM_GRAD: 4
#driver_PWM_AMPL: 128
#driver_SGT: 0
#diag1_pin:

[stepper_y]
step_pin: ar60
dir_pin: !ar61
enable_pin: !ar56
step_distance: .0125
endstop_pin: ^!ar14
position_endstop: 0
position_min: 0
position_max: 200
homing_speed: 30
homing_retract_dist: 2
second_homing_speed: 1
homing_positive_dir: false

[tmc2130 stepper_y]
cs_pin: ar64
microsteps: 16
interpolate: True
run_current: .8
hold_current: .1
sense_resistor: 0.110
stealthchop_threshold: 200
#driver_IHOLDDELAY: 8
#driver_TPOWERDOWN: 0
#driver_TBL: 1
#driver_TOFF: 4
#driver_HEND: 7
#driver_HSTRT: 0
#driver_PWM_AUTOSCALE: True
#driver_PWM_FREQ: 1
#driver_PWM_GRAD: 4
#driver_PWM_AMPL: 128
#driver_SGT: 0
#diag1_pin:

[stepper_z]
step_pin: ar46
dir_pin: ar48
enable_pin: !ar62
step_distance: .0025
endstop_pin: probe:z_virtual_endstop
position_endstop: 0
position_min: -0.8
position_max: 185
homing_speed: 10
homing_retract_dist: 2
second_homing_speed: 1
homing_positive_dir: false

[tmc2130 stepper_z]
cs_pin: ar40 
microsteps: 16
interpolate: True
run_current: .8
hold_current: .3
sense_resistor: 0.110
stealthchop_threshold: 200
#driver_IHOLDDELAY: 8
#driver_TPOWERDOWN: 0
#driver_TBL: 1
#driver_TOFF: 4
#driver_HEND: 7
#driver_HSTRT: 0
#driver_PWM_AUTOSCALE: True
#driver_PWM_FREQ: 1
#driver_PWM_GRAD: 4
#driver_PWM_AMPL: 128
#driver_SGT: 0
#diag1_pin:

[stepper_z1]
step_pin: ar36
dir_pin: ar34
enable_pin: !ar30
step_distance: .0025

[tmc2130 stepper_z1]
cs_pin: ar59 
microsteps: 16
interpolate: True
run_current: .8
hold_current: .3
sense_resistor: 0.110
stealthchop_threshold: 200
#driver_IHOLDDELAY: 8
#driver_TPOWERDOWN: 0
#driver_TBL: 1
#driver_TOFF: 4
#driver_HEND: 7
#driver_HSTRT: 0
#driver_PWM_AUTOSCALE: True
#driver_PWM_FREQ: 1
#driver_PWM_GRAD: 4
#driver_PWM_AMPL: 128
#driver_SGT: 0
#diag1_pin:

[extruder]
step_pin: ar26
dir_pin: ar28
enable_pin: !ar24
step_distance: .002412
nozzle_diameter: 0.400
filament_diameter: 1.750
instantaneous_corner_velocity: 1.000
max_extrude_only_distance: 101.0
pressure_advance: 0.125
pressure_advance_smooth_time: 0.040
heater_pin: ar10
max_power: 1.0
sensor_type: ATC Semitec 104GT-2
sensor_pin: analog13
pullup_resistor: 4700
control = pid
pid_kp = 22.535
pid_ki = 1.156
pid_kd = 109.859
min_extrude_temp: 170
min_temp: 0
max_temp: 275

#Black PETG pressure_advance .11

[tmc2130 extruder]
cs_pin: ar42 
microsteps: 16
interpolate: True
run_current: .8
hold_current: .3
sense_resistor: 0.110
stealthchop_threshold: 200
#driver_IHOLDDELAY: 8
#driver_TPOWERDOWN: 0
#driver_TBL: 1
#driver_TOFF: 4
#driver_HEND: 7
#driver_HSTRT: 0
#driver_PWM_AUTOSCALE: True
#driver_PWM_FREQ: 1
#driver_PWM_GRAD: 4
#driver_PWM_AMPL: 128
#driver_SGT: 0
#diag1_pin:

[virtual_sdcard]
path: ~/sdcard

[pause_resume]
[display_status]

[temperature_sensor 12V]
sensor_type: NTC 100K beta 3950
sensor_pin: aux:analog9
min_temp: 15
max_temp: 60
gcode_id: 12V

[temperature_fan 24V_psu]
pin: aux:ar8
max_power: 1.0
shutdown_speed: 0
cycle_time: 0.010
hardware_pwm: false
kick_start_time: 0.100
sensor_type: NTC 100K beta 3950
sensor_pin: aux:analog15
min_temp:15
max_temp:60
target_temp: 29
max_speed: 0.7
min_speed: 0.3
control: watermark
#pid_Kp: 40
#pid_Ki: 0.2
#pid_Kd: 0.1
#pid_deriv_time: 1.0
#pid_integral_max: 0.75
gcode_id: 24V_psu

[temperature_fan tmc2130]
pin: aux:ar36
max_power: 1.0
shutdown_speed: 0
cycle_time: 0.010
hardware_pwm: false
kick_start_time: 0.100
sensor_type: NTC 100K beta 3950
sensor_pin: aux:analog13
min_temp: 12
max_temp: 60
target_temp: 36
max_speed: 1.0
min_speed: 0.3
control: watermark
gcode_id: tmc2130_Y

[temperature_fan rasppi]
pin: aux:ar34
max_power: 1
shutdown_speed: 0
cycle_time: 0.010
hardware_pwm: false
kick_start_time: 0.100
sensor_type: NTC 100K beta 3950
sensor_pin: aux:analog14
min_temp: 12
max_temp: 60
target_temp: 36
max_speed: 0.5
min_speed: 0.001
control: watermark
gcode_id: rasppi

[heater_fan extruder_fan]
pin: aux:ar10
max_power: 1
shutdown_speed: 0
heater: extruder
heater_temp: 50.0
fan_speed: 1.0

[heater_bed]
heater_pin: ar8
sensor_type: NTC 100K beta 3950
sensor_pin: analog14
#control: watermark
min_temp: 0
max_temp: 115

[servo my_servo]
pin: ar11
maximum_servo_angle: 90
minimum_pulse_width: 0.001
maximum_pulse_width: 0.002
initial_angle: 90

[gcode_macro pin_release]
gcode:
	SET_SERVO SERVO=my_servo ANGLE=35
	
[gcode_macro pin_retract]
gcode:
	SET_SERVO SERVO=my_servo ANGLE=88

[homing_override]
set_position_z: 0
axes: z
gcode:
    G28 X0 Y0
	G4 P500
    G1 X100 Y100 F3600
	pin_release
	G4 P500
	G28 Z0
	G4 P500
	pin_retract
	G4
	G1 Z10
	G1 X0 Y0

[gcode_macro accuracy36]
gcode:
	pin_release
	G4 P500
	PROBE_ACCURACY SPEED=3 SAMPLES=36
	pin_retract

[gcode_macro accuracy60]
gcode:
	pin_release
	G4 P500
	PROBE_ACCURACY SPEED=3 SAMPLES=60
	pin_retract
	
[gcode_macro accuracy100]
gcode:
	pin_release
	G4 P500
	PROBE_ACCURACY SPEED=3 SAMPLES=100
	pin_retract

[gcode_macro probe_cal]
gcode:
	pin_release
	G4 P500
	PROBE_CALIBRATE
	pin_retract

[gcode_macro z_tilt]
gcode:
	pin_release
	G4 P500
	Z_TILT_ADJUST
	pin_retract
	G1 X0 Y0 Z10 F3600
	
[gcode_macro bed_mesh]
gcode:
   pin_release
	BED_MESH_CLEAR
	G4 P500
	BED_MESH_CALIBRATE
	pin_retract

[gcode_macro bed_calibrate]
gcode:
	pin_release
	G4 P500
	Z_TILT_ADJUST
	G4
	BED_MESH_CLEAR
	G4 P500
	BED_MESH_CALIBRATE
	pin_retract

[probe]
pin: ar6
x_offset: 24.5
y_offset: 1.0
z_offset: .920
speed: 5.0

[z_tilt]
z_positions: 1,100
	173,100
points: 1,100
	173,100
speed: 50
horizontal_move_z: 5
retries: 10
retry_tolerance: .0025

[bed_mesh]
speed: 50
mesh_min: 25,2
mesh_max: 200,199
probe_count: 10,10
split_delta_z: .025
move_check_distance: 5.0
mesh_pps: 2,2
algorithm: bicubic
bicubic_tension: .1
	
[mcu]
serial: /dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_557363038313517091E1-if00
pin_map: arduino

[mcu aux]
serial: /dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_55739323031351518002-if00
pin_map: arduino

[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 3000
max_z_velocity: 5
max_z_accel: 100

[output_pin psupower]
pin: !ar12

[gcode_macro M80]
gcode: SET_PIN PIN=psupower VALUE=1

[gcode_macro M81]
gcode: SET_PIN PIN=psupower VALUE=0

[gcode_macro M300]
gcode: SET_PIN PIN=lcd VALUE=1

[gcode_macro M301]
gcode: SET_PIN PIN=lcd VALUE=0


# "RepRapDiscount 2004 Smart Controller" type displays
[display]
lcd_type: hd44780
rs_pin: aux:ar16
e_pin: aux:ar17
d4_pin: aux:ar23
d5_pin: aux:ar25
d6_pin: aux:ar27
d7_pin: aux:ar29
encoder_pins: ^aux:ar31, ^aux:ar33
click_pin: ^!aux:ar35

[output_pin lcd]
pin: aux:ar11

[output_pin fan2]
pin: aux:analog7
pwm: True
value: 0
shutdown_value: 0
cycle_time: 0.100
hardware_pwm: False

[output_pin fan3]
pin: aux:analog6
pwm: True
value: 0
shutdown_value: 0
cycle_time: 0.100
hardware_pwm: False

#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [heater_bed]
#*# pid_kp = 69.316
#*# pid_ki = 2.471
#*# pid_kd = 486.077
#*# control = pid
#*#
#*# [bed_mesh default]
#*# version = 1
#*# points =
#*# 	-0.047585, -0.027585, -0.010085, -0.002585, -0.002585, -0.010085, -0.022585, -0.030085, -0.042585, -0.052585
#*# 	-0.047585, -0.030085, -0.015085, -0.005085, -0.000085, -0.005085, -0.017585, -0.022585, -0.037585, -0.050085
#*# 	-0.032585, -0.020085, -0.010085, 0.002415, 0.004915, 0.002415, -0.007585, -0.020085, -0.030085, -0.035085
#*# 	-0.027585, -0.010085, 0.002415, 0.012415, 0.017415, 0.017415, 0.007415, -0.002585, -0.015085, -0.025085
#*# 	-0.002585, 0.004915, 0.019915, 0.034915, 0.029915, 0.024915, 0.017415, 0.004915, -0.012585, -0.020085
#*# 	0.004915, 0.019915, 0.032415, 0.042415, 0.044915, 0.042415, 0.032415, 0.024915, 0.009915, -0.002585
#*# 	0.017415, 0.029915, 0.047415, 0.054915, 0.054915, 0.057415, 0.044915, 0.034915, 0.022415, 0.009915
#*# 	0.009915, 0.024915, 0.039915, 0.052415, 0.059915, 0.057415, 0.052415, 0.039915, 0.032415, 0.014915
#*# 	-0.005085, 0.017415, 0.029915, 0.044915, 0.059915, 0.062415, 0.057415, 0.054915, 0.042415, 0.034915
#*# 	-0.055085, -0.027585, -0.002585, 0.017415, 0.029915, 0.042415, 0.049915, 0.044915, 0.044915, 0.044915
#*# x_count = 10
#*# y_count = 10
#*# mesh_x_pps = 2
#*# mesh_y_pps = 2
#*# algo = bicubic
#*# tension = 0.1
#*# min_x = 25.0
#*# max_x = 199.9625
#*# min_y = 2.00000000002
#*# max_y = 198.925

**Comment by krpepe** [comment]
![mainsail height map](https://user-images.githubusercontent.com/26741528/93670600-20aa6b80-fa62-11ea-8845-06533523891c.png)

[klippy.zip](https://github.com/meteyou/mainsail/files/5250104/klippy.zip)

**Comment by krpepe** [comment]
Is there anything else you need?

**Comment by krpepe** [comment]
@meteyou This is what I replaced my gcode_macro bed_mesh with and it didn't work

[gcode_macro BED_MESH_CALIBRATE]
rename_existing: BASE_BED_MESH_CALIBRATE
gcode:
    pin_release
	BED_MESH_CLEAR
	G4 P500
	BASE_BED_MESH_CALIBRATE
	pin_retract

**Comment by meteyou** [comment]
i don't see this in your log, but this should work. maybe you forget the tab before each gcode line?

but... the main problem is, that i cannot find a line with "rename" in your logfiles, so your config is not correct. but this is all a klipper config issue and not a mainsail issue.

**Comment by krpepe** [comment]
@meteyou 
![Untitled](https://user-images.githubusercontent.com/26741528/93686297-f0bb9200-fa7a-11ea-9485-61e2eab3c55d.png)
[klippy.log](https://github.com/meteyou/mainsail/files/5250394/klippy.log)

**Comment by krpepe** [comment]
@meteyou As you can see from the screen shot it would appear to be there  but in klippy log it isn't. Which config needs to be changed? As you can see I am changing it with the editor in mainsail and it modifies the one in pi\klipper_config\printer.cfg. does the original need to be modified as well?
![untitled1](https://user-images.githubusercontent.com/26741528/93686414-b272a280-fa7b-11ea-8a9d-69020059968e.png)

![Untitled](https://user-images.githubusercontent.com/26741528/93686323-1e084000-fa7b-11ea-9048-83f6e221bddb.png)
[klippy.log](https://github.com/meteyou/mainsail/files/5250398/klippy.log)

**Comment by meteyou** [comment]
work other changes? is it your correct printer.cfg? check your /etc/default/klipper, if you set it to /home/pi/klipper_config/printer.cfg.

**Comment by krpepe** [comment]
That was it! Thank you so much! I am sorry for my mistake! Thank you for taking the time to help me figure it out!
Have a great weekend!

Kevin

**Comment by meteyou** [comment]
@krpepe i added this macro overwrite in my docs now -> [https://github.com/meteyou/mainsail/blob/master/docs/macros.md#customize-klipper-default-commands](https://github.com/meteyou/mainsail/blob/master/docs/macros.md#customize-klipper-default-commands)
