### ISSUE TITLE
Remove unused Javascript Files

### ISSUE THREAD

**Issue by translucentfocus** [meteyou/mainsail#79]
**Describe the bug:**\
Lighthouse reports that there are two js files (one that's rather large) that are unused.

**Expected behavior:**\
Unused javascript files should be removed

**Screenshots:**\
![image](https://user-images.githubusercontent.com/26986716/93730432-361cb400-fb8e-11ea-91d5-6352b9b503ef.png)

**Logfiles:**\
I don't believe logs are necessary for this issue.  However, version info may be important.  I am running `v0.2.2 - v0.8.0-779-g91979756`

**Comment by meteyou** [comment]
do you know, that mainsail is a vue.js project with the framework vuetify? the app.5dc990c3.js is the main code of mainsail itself. chunk-vendors.js is the most part of the framework. if you think a seo tool handle a webapp, give it a try and delete this files ;-)

**Comment by translucentfocus** [comment]
Sorry for wasting your time!  I am aware it's a Vue app with Vuetify (and it's awesome btw).  I guess deleting the main web app would make it faster 🤣
