### ISSUE TITLE
refreshing the webcam page returns 502 Bad Gateway

### ISSUE THREAD

**Issue by LazaroFilm** [meteyou/mainsail#81]
**Describe the bug:**\
On the Webcam page, hit refresh. Or, going to the address `myprinter.local/webcam/` shows a `502 Bad Gateway
nginx/1.14.2`

**Expected behavior:**\
See the webcam page.

**Screenshots:**\
<img width="609" alt="Screen Shot 2020-09-22 at 4 22 45 PM" src="https://user-images.githubusercontent.com/18351100/93933587-de965980-fcef-11ea-8787-3c02f93b3bb3.png">

**Logfiles:**\
Please upload your Logfiles here or upload them to [pastebin.com](http://pastebin.com) and paste your log links here.
- [klippy (1).log](https://github.com/meteyou/mainsail/files/5263829/klippy.1.log)
- [moonraker (1).log](https://github.com/meteyou/mainsail/files/5263835/moonraker.1.log)

**Comment by meteyou** [comment]
do you install & configure mjpgstreamer or something else for your webcam?

**Comment by LazaroFilm** [comment]
I followed [these instructions](https://3dp.tumbleweedlabs.com/firmware/klipper-firmware/adding-webcam-support-to-mainsail) (with some tweaks to get raspicam working)

**Comment by meteyou** [comment]
thx for the report. mainsail route to /webcam and nginx have a redirect for /webcam to port 8080 (mjpgstreamer). this is the problem, why you are redirect after a refresh.

your error 502 comes from your mjpgstreamer setup. this is no mainsail issue.
