### ISSUE TITLE
Weird temperature display after loosing connection

### ISSUE THREAD

**Issue by david-sawatzke** [meteyou/mainsail#82]
**Describe the bug:**\
Shortly before the print ended, my pc went into suspend. After I woke it up, I immediately changed the target temperatures and the temperature display did very weird things 

**Expected behavior:**\
At least make the lines make mathematical sense

**Screenshots:**\
![Screenshot_2020-09-23 Complete - CE3_ledprofile gcode](https://user-images.githubusercontent.com/11035569/94035820-dc053400-fdc3-11ea-98e3-7661945b9a63.png)

**Comment by MarcPot** [comment]
Ah, I thought it was the phone version of the webpage. But this sounds more probable.

My phone disconnects every time I open another app, and when I return I get the same problem.

![Uploading 4C844365-ACF8-4740-8928-9DAAD3E6E012.png…]()
