### ISSUE TITLE
Setting chamber temperature in web interface

### ISSUE THREAD

**Issue by khumarahn** [meteyou/mainsail#87]
Hi, I set up mainsail today from the current repo. My printer has a chamber heater, defined in printer.cfg with
```
[heater_generic chamber_heater]
gcode_id: C
...
```

When I attempt to set its temperature in the web interface, I get an error
```
!! Malformed command 'SET_HEATER_TEMPERATURE HEATER=heater_generic chamber_heater TARGET=50'
```
I guess the command should be
```
SET_HEATER_TEMPERATURE HEATER=chamber_heater TARGET=50
```

**Comment by meteyou** [comment]
ahh. thx for the bugreport. i only use/tested extruders, heater_bed and temperature_fans but no heater_generic. i will update this.

**Comment by khumarahn** [comment]
Hi. I get the same error with version 0.23. (thanks for the new version!!)

**Comment by aka13-404** [comment]
Can confirm it still happening, web interface looks strange as well. See attached screenshots.
![image](https://user-images.githubusercontent.com/51682059/96353562-89225200-10cd-11eb-8a92-342f6b88ce68.png)
![image](https://user-images.githubusercontent.com/51682059/96353555-80318080-10cd-11eb-9ab3-601792a9a36d.png)
![image](https://user-images.githubusercontent.com/51682059/96353579-9fc8a900-10cd-11eb-8883-b5aaeefae293.png)

**Comment by khumarahn** [comment]
is this with 0.24?

@meteyou maybe re-open this issue?

**Comment by meteyou** [comment]
pls test the attached build. i test it only with a thermistor...

[mainsail-beta-nightly-heater_generic.zip](https://github.com/meteyou/mainsail/files/5397563/mainsail-beta-nightly-heater_generic.zip)

**Comment by khumarahn** [comment]
Thanks! I installed everything with kiauh, as a side effect I don't know how to do anything manually. What is the easiest way to try this build?

**Comment by khumarahn** [comment]
Say, is it enough to override `/home/pi/mainsail' with the contents of the archive? Does mainsail save any settings in `/home/pi/mainsail'?

**Comment by meteyou** [comment]
`
cd ~/mainsail
rm -R ./*
wget -q -O mainsail.zip https://github.com/meteyou/mainsail/files/5397563/mainsail-beta-nightly-heater_generic.zip && unzip mainsail.zip && rm mainsail.zip
`
and then open mainsail and refresh with CTRL+SHIFT+R for reload without cache.

**Comment by khumarahn** [comment]
It looks like it works. So far I updated mainsail and changed chamber temperature in the middle of the print, and it looks like it worked. I will try again soon when the print finishes.

**Comment by meteyou** [comment]
thx. if it works without problems, pls close this issue. this update should be in the next version.

**Comment by aka13-404** [comment]
Works great, no issues, the view as well as temperature setting work as expected now.
Thank you for the quick fix.
![image](https://user-images.githubusercontent.com/51682059/96369109-540f1180-1158-11eb-9363-ed778763fc6a.png)
![image](https://user-images.githubusercontent.com/51682059/96369170-c08a1080-1158-11eb-8dcc-4283d5a71028.png)

**Comment by khumarahn** [comment]
@meteyou While you are at it, is it hard to make the chamber heater appear after all other heaters?

**Comment by meteyou** [comment]
@khumarahn heaters are sorted alphabetically. only the temperature_fans come afterwards...

**Comment by khumarahn** [comment]
ok, so I can name my heater zzz_chamber_heater and it will be in the end.

Thanks!

**Comment by khumarahn** [comment]
Double checked after the print finished, it works. Many thanks!!!!! and I am closing this issue.
