### ISSUE TITLE
Last modified time is actually showing the file creation time

### ISSUE THREAD

**Issue by tionebrr** [meteyou/mainsail#89]
Well all is in the title.
Using a RPI3B+, everything up-to-date.

View from windows (via samba):
![image](https://user-images.githubusercontent.com/8854321/94876150-1a02f780-0457-11eb-96c9-c33a9ab97ffd.png)
View from Mainsail:
![image](https://user-images.githubusercontent.com/8854321/94876174-2d15c780-0457-11eb-91ba-aa91fd5f213b.png)

**Comment by meteyou** [comment]
without logfiles, there is nothing I can do...

**Comment by tionebrr** [comment]
Sure, here they are:
[klippy.log](https://github.com/meteyou/mainsail/files/5317758/klippy.log)
[moonraker.log](https://github.com/meteyou/mainsail/files/5317759/moonraker.log)

**Comment by theopensourcerer** [comment]
@meteyou I think he's right. I ssh'ed into my RPi and modified one of the gcode files using nano. Then I refreshed the browser:

![Screenshot from 2020-10-02 13-21-06](https://user-images.githubusercontent.com/3414988/94922755-ae4e7800-04b2-11eb-8065-8a2dd57e87fb.png)

**Comment by theopensourcerer** [comment]
Sorry mainsail version: v0.2.2 - v0.8.0-765-g1f3a160f

**Comment by meteyou** [comment]
ok. i think moonraker extract the wrong date from the files. i redirect it to Arksine...

**Comment by tionebrr** [comment]
Thanks @meteyou

**Comment by meteyou** [comment]
should be fixed in moonraker...

**Comment by tionebrr** [comment]
Hi, just updated and it's looking good. Thanks a lot.
