### ISSUE TITLE
Incorrect Line info given

### ISSUE THREAD

**Issue by paulhew69** [meteyou/mainsail#92]
Incorrect Line info given.

Correct Line info given

**Screenshots:**\
![image](https://user-images.githubusercontent.com/61477100/95013715-01066c00-063a-11eb-98c9-17187fe99b4d.png)

Line 119 in my config is this, nothing to do with Print_Start macro

[klippy.log](https://github.com/meteyou/mainsail/files/5323056/klippy.log)
[moonraker.log](https://github.com/meteyou/mainsail/files/5323057/moonraker.log)
Line 119 in my config is this. 'hold_current: 0.9'

**Logfiles:**\
Please upload your Logfiles here or upload them to [pastebin.com](http://pastebin.com) and paste your log links here.
- klippy.log
- moonraker.log

**Comment by meteyou** [comment]
this message comes from klipper. mainsail only display it 1:1. i think the line numbers are without comment lines.
