### ISSUE TITLE
Refresh needed for interface settings when psu is not always on.

### ISSUE THREAD

**Issue by MarcPot** [meteyou/mainsail#96]
**Describe the bug:**\
Because my PSU is connected to a relay, Klipper is never connected on startup, this causes the mainsail interface settings to not load when I load the page.
After I do a restart so klipper can connect to my MCU I need to refresh the page to load the interface settings.

Edit: This only happens the first time, after the settings are loaded they stay loaded.

**Expected behavior:**\
I expect the interface settings to load even when Klipper can't connect.

**Screenshots:**\
Screenshot of what I see before the refresh.
![image](https://user-images.githubusercontent.com/7275765/95504509-1e766580-09ad-11eb-8ac8-66bf38f45348.png)
Screenshot of what I see after the refresh.
![image](https://user-images.githubusercontent.com/7275765/95504606-4c5baa00-09ad-11eb-863c-c1bb70a77943.png)

**Logfiles:**\
Please upload your Logfiles here or upload them to [pastebin.com](http://pastebin.com) and paste your log links here.
[moonraker.log](https://github.com/meteyou/mainsail/files/5350929/moonraker.log)
[klippy.log](https://github.com/meteyou/mainsail/files/5350930/klippy.log)

**Comment by meteyou** [comment]
this is a problem of V0.2.2. should be fixed in V0.2.3. pls test it again with the next version. but i think we talked about it on discord already 2 times about this issue...

**Comment by MarcPot** [comment]
Yea but I opened this issue because I found the cause. And on Discord I only had the problem. Thanks anyways for fixing it!

**Comment by meteyou** [comment]
@MarcPot can we close this issue?

**Comment by MarcPot** [comment]
@meteyou I haven’t been able to test it because of personal problems. But if you day it’s fixed it’s fixed.
