### ISSUE TITLE
gcode macro formatting issue on dashboard

### ISSUE THREAD

**Issue by pheonix3330** [meteyou/mainsail#98]
**Describe the bug:**\
When a macro has more then 2 words, mainsail only deletes the first underscore between the first and second word. the underscore character is still between subsequent words.

**Expected behavior:**\
Mainsail should delete all instances of underscore and replace with spaces.

**Screenshots:**\
![image](https://user-images.githubusercontent.com/62308091/95537270-440a6b80-09bb-11eb-82a3-467578a8764e.png)

**Comment by meteyou** [comment]
fixed -> https://github.com/meteyou/mainsail/commit/8220642774a7a12a0e8eff51db2846a0bf334a24
